/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.4.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDateEdit>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QStackedWidget *stackedWidget;
    QWidget *GiaoDienChinh0;
    QLabel *label0;
    QPushButton *pushButton_1;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QPushButton *pushButton_5;
    QWidget *Them1;
    QLabel *label0_2;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QRadioButton *radioButtonTaiLieu;
    QTextEdit *textEditDiaChiGui;
    QCheckBox *checkBoxDenChua;
    QRadioButton *radioButton_2;
    QTextEdit *textEditDiaChiNhan;
    QLabel *label_5;
    QTextEdit *textEditQuangDuong;
    QTextEdit *textEdit_7;
    QLabel *label_8;
    QPushButton *pushButton_23;
    QPushButton *pushButton;
    QDateEdit *dateEditNgayGui;
    QLabel *label_25;
    QTextEdit *textEditTenNguoiGui;
    QLabel *label_26;
    QTextEdit *textEditTenNguoiNhan;
    QDateEdit *dateEditNgayNhan;
    QWidget *ThemThanhCong3;
    QLabel *label0_3;
    QLabel *label0_4;
    QLabel *label0_5;
    QWidget *verticalLayoutWidget;
    QVBoxLayout *verticalLayout;
    QLabel *label_28;
    QLabel *label_27;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_15;
    QLabel *label_14;
    QLabel *label_13;
    QLabel *label_16;
    QPushButton *pushButton_18;
    QPushButton *pushButton_20;
    QLabel *labelID;
    QLabel *labelDiaChiGui;
    QLabel *labelDiaChiNhan;
    QLabel *labelQuangDuong;
    QLabel *labelTaiLieuHayBuuKien;
    QLabel *labelNgayThangNamGui;
    QLabel *labelNgayThangNamNhan;
    QLabel *labelTenNguoiGui;
    QLabel *labelTenNguoiNhan;
    QWidget *CapNhatGia3;
    QLabel *label0_11;
    QCheckBox *checkBox_5;
    QCheckBox *checkBox_6;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label0_12;
    QLabel *label0_13;
    QLabel *label0_14;
    QLabel *label0_15;
    QTextEdit *textEdit_40;
    QTextEdit *textEdit_41;
    QTextEdit *textEdit_42;
    QTextEdit *textEdit_43;
    QPushButton *pushButton_13;
    QPushButton *pushButton_15;
    QPushButton *pushButton_22;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QLabel *label_54;
    QWidget *DoanhThu4;
    QLabel *label0_16;
    QLabel *label0_17;
    QLabel *label0_18;
    QLabel *label0_19;
    QLabel *label0_20;
    QLabel *label0_21;
    QPushButton *pushButton_21;
    QLabel *label_6;
    QDateEdit *dateEdit;
    QDateEdit *dateEdit_2;
    QTableWidget *tableWidgetDSDoanhThu;
    QPushButton *pushButton_6;
    QWidget *DanhSachDoanhThu5;
    QLabel *label0_22;
    QPushButton *pushButton_24;
    QPushButton *pushButton_25;
    QWidget *TimTheoDiaChi6;
    QLabel *label0_23;
    QLabel *label0_24;
    QTextEdit *textEdit_52;
    QPushButton *pushButton_26;
    QTableWidget *tableWidgetDSDiaChi;
    QPushButton *pushButton_7;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName("MainWindow");
        MainWindow->resize(886, 564);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName("centralwidget");
        stackedWidget = new QStackedWidget(centralwidget);
        stackedWidget->setObjectName("stackedWidget");
        stackedWidget->setGeometry(QRect(10, 0, 871, 531));
        QFont font;
        font.setPointSize(16);
        stackedWidget->setFont(font);
        stackedWidget->setAutoFillBackground(false);
        GiaoDienChinh0 = new QWidget();
        GiaoDienChinh0->setObjectName("GiaoDienChinh0");
        label0 = new QLabel(GiaoDienChinh0);
        label0->setObjectName("label0");
        label0->setGeometry(QRect(330, 90, 198, 36));
        QFont font1;
        font1.setFamilies({QString::fromUtf8("Segoe UI")});
        font1.setPointSize(20);
        font1.setBold(true);
        label0->setFont(font1);
        pushButton_1 = new QPushButton(GiaoDienChinh0);
        pushButton_1->setObjectName("pushButton_1");
        pushButton_1->setGeometry(QRect(100, 80, 671, 61));
        QFont font2;
        font2.setFamilies({QString::fromUtf8("Segoe UI")});
        font2.setPointSize(18);
        font2.setBold(true);
        pushButton_1->setFont(font2);
        pushButton_2 = new QPushButton(GiaoDienChinh0);
        pushButton_2->setObjectName("pushButton_2");
        pushButton_2->setGeometry(QRect(500, 210, 311, 81));
        pushButton_2->setFont(font2);
        pushButton_3 = new QPushButton(GiaoDienChinh0);
        pushButton_3->setObjectName("pushButton_3");
        pushButton_3->setGeometry(QRect(60, 370, 301, 91));
        pushButton_3->setFont(font2);
        pushButton_4 = new QPushButton(GiaoDienChinh0);
        pushButton_4->setObjectName("pushButton_4");
        pushButton_4->setGeometry(QRect(60, 210, 301, 81));
        pushButton_4->setFont(font2);
        pushButton_5 = new QPushButton(GiaoDienChinh0);
        pushButton_5->setObjectName("pushButton_5");
        pushButton_5->setGeometry(QRect(500, 370, 311, 91));
        pushButton_5->setFont(font2);
        stackedWidget->addWidget(GiaoDienChinh0);
        pushButton_1->raise();
        label0->raise();
        pushButton_2->raise();
        pushButton_3->raise();
        pushButton_4->raise();
        pushButton_5->raise();
        Them1 = new QWidget();
        Them1->setObjectName("Them1");
        label0_2 = new QLabel(Them1);
        label0_2->setObjectName("label0_2");
        label0_2->setGeometry(QRect(430, 0, 81, 41));
        QFont font3;
        font3.setFamilies({QString::fromUtf8("Segoe UI")});
        font3.setPointSize(22);
        font3.setBold(true);
        label0_2->setFont(font3);
        label0_2->setAutoFillBackground(false);
        label = new QLabel(Them1);
        label->setObjectName("label");
        label->setGeometry(QRect(20, 191, 73, 28));
        QFont font4;
        font4.setPointSize(16);
        font4.setBold(true);
        label->setFont(font4);
        label_2 = new QLabel(Them1);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(20, 260, 90, 28));
        label_2->setFont(font4);
        label_3 = new QLabel(Them1);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(20, 410, 97, 28));
        label_3->setFont(font4);
        label_4 = new QLabel(Them1);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(20, 310, 142, 28));
        label_4->setFont(font4);
        radioButtonTaiLieu = new QRadioButton(Them1);
        radioButtonTaiLieu->setObjectName("radioButtonTaiLieu");
        radioButtonTaiLieu->setGeometry(QRect(180, 310, 94, 34));
        radioButtonTaiLieu->setFont(font4);
        textEditDiaChiGui = new QTextEdit(Them1);
        textEditDiaChiGui->setObjectName("textEditDiaChiGui");
        textEditDiaChiGui->setGeometry(QRect(120, 180, 461, 41));
        QFont font5;
        font5.setPointSize(14);
        textEditDiaChiGui->setFont(font5);
        checkBoxDenChua = new QCheckBox(Them1);
        checkBoxDenChua->setObjectName("checkBoxDenChua");
        checkBoxDenChua->setGeometry(QRect(440, 410, 275, 34));
        checkBoxDenChua->setFont(font4);
        radioButton_2 = new QRadioButton(Them1);
        radioButton_2->setObjectName("radioButton_2");
        radioButton_2->setGeometry(QRect(180, 350, 113, 34));
        radioButton_2->setFont(font4);
        textEditDiaChiNhan = new QTextEdit(Them1);
        textEditDiaChiNhan->setObjectName("textEditDiaChiNhan");
        textEditDiaChiNhan->setGeometry(QRect(120, 250, 461, 41));
        textEditDiaChiNhan->setFont(font5);
        label_5 = new QLabel(Them1);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(680, 210, 138, 28));
        label_5->setFont(font4);
        textEditQuangDuong = new QTextEdit(Them1);
        textEditQuangDuong->setObjectName("textEditQuangDuong");
        textEditQuangDuong->setGeometry(QRect(670, 250, 161, 41));
        textEditQuangDuong->setFont(font5);
        textEdit_7 = new QTextEdit(Them1);
        textEdit_7->setObjectName("textEdit_7");
        textEdit_7->setGeometry(QRect(300, 340, 161, 41));
        textEdit_7->setFont(font5);
        label_8 = new QLabel(Them1);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(480, 350, 52, 28));
        label_8->setFont(font4);
        pushButton_23 = new QPushButton(Them1);
        pushButton_23->setObjectName("pushButton_23");
        pushButton_23->setGeometry(QRect(720, 0, 151, 40));
        QFont font6;
        font6.setPointSize(11);
        font6.setBold(false);
        pushButton_23->setFont(font6);
        pushButton = new QPushButton(Them1);
        pushButton->setObjectName("pushButton");
        pushButton->setGeometry(QRect(370, 470, 151, 41));
        QFont font7;
        font7.setPointSize(11);
        pushButton->setFont(font7);
        dateEditNgayGui = new QDateEdit(Them1);
        dateEditNgayGui->setObjectName("dateEditNgayGui");
        dateEditNgayGui->setGeometry(QRect(130, 410, 111, 31));
        dateEditNgayGui->setFont(font7);
        label_25 = new QLabel(Them1);
        label_25->setObjectName("label_25");
        label_25->setGeometry(QRect(20, 70, 138, 28));
        label_25->setFont(font4);
        textEditTenNguoiGui = new QTextEdit(Them1);
        textEditTenNguoiGui->setObjectName("textEditTenNguoiGui");
        textEditTenNguoiGui->setGeometry(QRect(170, 60, 481, 41));
        textEditTenNguoiGui->setFont(font5);
        label_26 = new QLabel(Them1);
        label_26->setObjectName("label_26");
        label_26->setGeometry(QRect(20, 130, 163, 28));
        label_26->setFont(font4);
        textEditTenNguoiNhan = new QTextEdit(Them1);
        textEditTenNguoiNhan->setObjectName("textEditTenNguoiNhan");
        textEditTenNguoiNhan->setGeometry(QRect(190, 119, 461, 41));
        textEditTenNguoiNhan->setFont(font5);
        dateEditNgayNhan = new QDateEdit(Them1);
        dateEditNgayNhan->setObjectName("dateEditNgayNhan");
        dateEditNgayNhan->setGeometry(QRect(720, 410, 111, 31));
        dateEditNgayNhan->setFont(font7);
        stackedWidget->addWidget(Them1);
        ThemThanhCong3 = new QWidget();
        ThemThanhCong3->setObjectName("ThemThanhCong3");
        label0_3 = new QLabel(ThemThanhCong3);
        label0_3->setObjectName("label0_3");
        label0_3->setGeometry(QRect(200, 20, 495, 39));
        label0_3->setFont(font3);
        label0_3->setAutoFillBackground(false);
        label0_4 = new QLabel(ThemThanhCong3);
        label0_4->setObjectName("label0_4");
        label0_4->setGeometry(QRect(260, 80, 212, 39));
        label0_4->setFont(font3);
        label0_4->setAutoFillBackground(false);
        label0_5 = new QLabel(ThemThanhCong3);
        label0_5->setObjectName("label0_5");
        label0_5->setGeometry(QRect(60, 140, 97, 26));
        QFont font8;
        font8.setFamilies({QString::fromUtf8("Segoe UI")});
        font8.setPointSize(16);
        font8.setBold(true);
        label0_5->setFont(font8);
        label0_5->setAutoFillBackground(false);
        verticalLayoutWidget = new QWidget(ThemThanhCong3);
        verticalLayoutWidget->setObjectName("verticalLayoutWidget");
        verticalLayoutWidget->setGeometry(QRect(180, 130, 281, 371));
        verticalLayout = new QVBoxLayout(verticalLayoutWidget);
        verticalLayout->setObjectName("verticalLayout");
        verticalLayout->setContentsMargins(0, 0, 0, 0);
        label_28 = new QLabel(verticalLayoutWidget);
        label_28->setObjectName("label_28");
        label_28->setFont(font4);

        verticalLayout->addWidget(label_28);

        label_27 = new QLabel(verticalLayoutWidget);
        label_27->setObjectName("label_27");
        label_27->setFont(font4);

        verticalLayout->addWidget(label_27);

        label_11 = new QLabel(verticalLayoutWidget);
        label_11->setObjectName("label_11");
        label_11->setFont(font4);

        verticalLayout->addWidget(label_11);

        label_12 = new QLabel(verticalLayoutWidget);
        label_12->setObjectName("label_12");
        label_12->setFont(font4);

        verticalLayout->addWidget(label_12);

        label_15 = new QLabel(verticalLayoutWidget);
        label_15->setObjectName("label_15");
        label_15->setFont(font4);

        verticalLayout->addWidget(label_15);

        label_14 = new QLabel(verticalLayoutWidget);
        label_14->setObjectName("label_14");
        label_14->setFont(font4);

        verticalLayout->addWidget(label_14);

        label_13 = new QLabel(verticalLayoutWidget);
        label_13->setObjectName("label_13");
        label_13->setFont(font4);

        verticalLayout->addWidget(label_13);

        label_16 = new QLabel(verticalLayoutWidget);
        label_16->setObjectName("label_16");
        label_16->setFont(font4);

        verticalLayout->addWidget(label_16);

        pushButton_18 = new QPushButton(ThemThanhCong3);
        pushButton_18->setObjectName("pushButton_18");
        pushButton_18->setGeometry(QRect(40, 200, 120, 40));
        QFont font9;
        font9.setPointSize(18);
        font9.setBold(true);
        pushButton_18->setFont(font9);
        pushButton_20 = new QPushButton(ThemThanhCong3);
        pushButton_20->setObjectName("pushButton_20");
        pushButton_20->setGeometry(QRect(720, 0, 151, 40));
        pushButton_20->setFont(font6);
        labelID = new QLabel(ThemThanhCong3);
        labelID->setObjectName("labelID");
        labelID->setGeometry(QRect(490, 80, 201, 41));
        labelID->setFont(font3);
        labelID->setAutoFillBackground(false);
        labelDiaChiGui = new QLabel(ThemThanhCong3);
        labelDiaChiGui->setObjectName("labelDiaChiGui");
        labelDiaChiGui->setGeometry(QRect(270, 230, 561, 31));
        labelDiaChiGui->setFont(font8);
        labelDiaChiGui->setAutoFillBackground(false);
        labelDiaChiNhan = new QLabel(ThemThanhCong3);
        labelDiaChiNhan->setObjectName("labelDiaChiNhan");
        labelDiaChiNhan->setGeometry(QRect(280, 280, 541, 31));
        labelDiaChiNhan->setFont(font8);
        labelDiaChiNhan->setAutoFillBackground(false);
        labelQuangDuong = new QLabel(ThemThanhCong3);
        labelQuangDuong->setObjectName("labelQuangDuong");
        labelQuangDuong->setGeometry(QRect(340, 330, 371, 26));
        labelQuangDuong->setFont(font8);
        labelQuangDuong->setAutoFillBackground(false);
        labelTaiLieuHayBuuKien = new QLabel(ThemThanhCong3);
        labelTaiLieuHayBuuKien->setObjectName("labelTaiLieuHayBuuKien");
        labelTaiLieuHayBuuKien->setGeometry(QRect(350, 420, 371, 26));
        labelTaiLieuHayBuuKien->setFont(font8);
        labelTaiLieuHayBuuKien->setAutoFillBackground(false);
        labelNgayThangNamGui = new QLabel(ThemThanhCong3);
        labelNgayThangNamGui->setObjectName("labelNgayThangNamGui");
        labelNgayThangNamGui->setGeometry(QRect(250, 370, 371, 26));
        labelNgayThangNamGui->setFont(font8);
        labelNgayThangNamGui->setAutoFillBackground(false);
        labelNgayThangNamNhan = new QLabel(ThemThanhCong3);
        labelNgayThangNamNhan->setObjectName("labelNgayThangNamNhan");
        labelNgayThangNamNhan->setGeometry(QRect(450, 470, 371, 26));
        labelNgayThangNamNhan->setFont(font8);
        labelNgayThangNamNhan->setAutoFillBackground(false);
        labelTenNguoiGui = new QLabel(ThemThanhCong3);
        labelTenNguoiGui->setObjectName("labelTenNguoiGui");
        labelTenNguoiGui->setGeometry(QRect(330, 140, 561, 26));
        labelTenNguoiGui->setFont(font8);
        labelTenNguoiGui->setAutoFillBackground(false);
        labelTenNguoiNhan = new QLabel(ThemThanhCong3);
        labelTenNguoiNhan->setObjectName("labelTenNguoiNhan");
        labelTenNguoiNhan->setGeometry(QRect(360, 180, 561, 26));
        labelTenNguoiNhan->setFont(font8);
        labelTenNguoiNhan->setAutoFillBackground(false);
        stackedWidget->addWidget(ThemThanhCong3);
        CapNhatGia3 = new QWidget();
        CapNhatGia3->setObjectName("CapNhatGia3");
        label0_11 = new QLabel(CapNhatGia3);
        label0_11->setObjectName("label0_11");
        label0_11->setGeometry(QRect(330, 0, 172, 39));
        label0_11->setFont(font3);
        label0_11->setAutoFillBackground(false);
        checkBox_5 = new QCheckBox(CapNhatGia3);
        checkBox_5->setObjectName("checkBox_5");
        checkBox_5->setGeometry(QRect(90, 70, 94, 34));
        checkBox_5->setFont(font4);
        checkBox_6 = new QCheckBox(CapNhatGia3);
        checkBox_6->setObjectName("checkBox_6");
        checkBox_6->setGeometry(QRect(90, 230, 279, 34));
        checkBox_6->setFont(font4);
        label_35 = new QLabel(CapNhatGia3);
        label_35->setObjectName("label_35");
        label_35->setGeometry(QRect(110, 130, 130, 26));
        QFont font10;
        font10.setPointSize(14);
        font10.setBold(true);
        label_35->setFont(font10);
        label_36 = new QLabel(CapNhatGia3);
        label_36->setObjectName("label_36");
        label_36->setGeometry(QRect(110, 180, 130, 26));
        label_36->setFont(font10);
        label_37 = new QLabel(CapNhatGia3);
        label_37->setObjectName("label_37");
        label_37->setGeometry(QRect(110, 290, 130, 26));
        label_37->setFont(font10);
        label_38 = new QLabel(CapNhatGia3);
        label_38->setObjectName("label_38");
        label_38->setGeometry(QRect(110, 350, 130, 26));
        label_38->setFont(font10);
        label0_12 = new QLabel(CapNhatGia3);
        label0_12->setObjectName("label0_12");
        label0_12->setGeometry(QRect(440, 120, 45, 39));
        label0_12->setFont(font3);
        label0_12->setAutoFillBackground(false);
        label0_13 = new QLabel(CapNhatGia3);
        label0_13->setObjectName("label0_13");
        label0_13->setGeometry(QRect(440, 180, 45, 39));
        label0_13->setFont(font3);
        label0_13->setAutoFillBackground(false);
        label0_14 = new QLabel(CapNhatGia3);
        label0_14->setObjectName("label0_14");
        label0_14->setGeometry(QRect(440, 280, 45, 39));
        label0_14->setFont(font3);
        label0_14->setAutoFillBackground(false);
        label0_15 = new QLabel(CapNhatGia3);
        label0_15->setObjectName("label0_15");
        label0_15->setGeometry(QRect(440, 340, 45, 39));
        label0_15->setFont(font3);
        label0_15->setAutoFillBackground(false);
        textEdit_40 = new QTextEdit(CapNhatGia3);
        textEdit_40->setObjectName("textEdit_40");
        textEdit_40->setGeometry(QRect(500, 120, 151, 41));
        QFont font11;
        font11.setPointSize(12);
        textEdit_40->setFont(font11);
        textEdit_41 = new QTextEdit(CapNhatGia3);
        textEdit_41->setObjectName("textEdit_41");
        textEdit_41->setGeometry(QRect(500, 180, 151, 41));
        textEdit_41->setFont(font11);
        textEdit_42 = new QTextEdit(CapNhatGia3);
        textEdit_42->setObjectName("textEdit_42");
        textEdit_42->setGeometry(QRect(500, 280, 151, 41));
        textEdit_42->setFont(font11);
        textEdit_43 = new QTextEdit(CapNhatGia3);
        textEdit_43->setObjectName("textEdit_43");
        textEdit_43->setGeometry(QRect(500, 340, 151, 41));
        textEdit_43->setFont(font11);
        pushButton_13 = new QPushButton(CapNhatGia3);
        pushButton_13->setObjectName("pushButton_13");
        pushButton_13->setGeometry(QRect(260, 420, 215, 44));
        pushButton_13->setFont(font9);
        pushButton_15 = new QPushButton(CapNhatGia3);
        pushButton_15->setObjectName("pushButton_15");
        pushButton_15->setGeometry(QRect(500, 420, 81, 41));
        pushButton_15->setFont(font9);
        pushButton_22 = new QPushButton(CapNhatGia3);
        pushButton_22->setObjectName("pushButton_22");
        pushButton_22->setGeometry(QRect(720, 0, 151, 40));
        pushButton_22->setFont(font6);
        label_51 = new QLabel(CapNhatGia3);
        label_51->setObjectName("label_51");
        label_51->setGeometry(QRect(294, 130, 131, 28));
        label_51->setFont(font9);
        label_51->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_52 = new QLabel(CapNhatGia3);
        label_52->setObjectName("label_52");
        label_52->setGeometry(QRect(294, 190, 131, 28));
        label_52->setFont(font9);
        label_52->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_53 = new QLabel(CapNhatGia3);
        label_53->setObjectName("label_53");
        label_53->setGeometry(QRect(294, 290, 131, 28));
        label_53->setFont(font9);
        label_53->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_54 = new QLabel(CapNhatGia3);
        label_54->setObjectName("label_54");
        label_54->setGeometry(QRect(294, 350, 131, 28));
        label_54->setFont(font9);
        label_54->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        stackedWidget->addWidget(CapNhatGia3);
        DoanhThu4 = new QWidget();
        DoanhThu4->setObjectName("DoanhThu4");
        label0_16 = new QLabel(DoanhThu4);
        label0_16->setObjectName("label0_16");
        label0_16->setGeometry(QRect(380, 10, 144, 39));
        label0_16->setFont(font3);
        label0_16->setAutoFillBackground(false);
        label0_17 = new QLabel(DoanhThu4);
        label0_17->setObjectName("label0_17");
        label0_17->setGeometry(QRect(30, 50, 252, 39));
        label0_17->setFont(font1);
        label0_17->setAutoFillBackground(false);
        label0_18 = new QLabel(DoanhThu4);
        label0_18->setObjectName("label0_18");
        label0_18->setGeometry(QRect(30, 160, 160, 39));
        label0_18->setFont(font1);
        label0_18->setAutoFillBackground(false);
        label0_19 = new QLabel(DoanhThu4);
        label0_19->setObjectName("label0_19");
        label0_19->setGeometry(QRect(550, 150, 75, 41));
        label0_19->setFont(font1);
        label0_19->setAutoFillBackground(false);
        label0_20 = new QLabel(DoanhThu4);
        label0_20->setObjectName("label0_20");
        label0_20->setGeometry(QRect(30, 100, 55, 36));
        label0_20->setFont(font1);
        label0_20->setAutoFillBackground(false);
        label0_21 = new QLabel(DoanhThu4);
        label0_21->setObjectName("label0_21");
        label0_21->setGeometry(QRect(250, 100, 72, 36));
        label0_21->setFont(font1);
        label0_21->setAutoFillBackground(false);
        pushButton_21 = new QPushButton(DoanhThu4);
        pushButton_21->setObjectName("pushButton_21");
        pushButton_21->setGeometry(QRect(720, 0, 151, 40));
        pushButton_21->setFont(font6);
        label_6 = new QLabel(DoanhThu4);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(200, 160, 321, 31));
        label_6->setFont(font5);
        dateEdit = new QDateEdit(DoanhThu4);
        dateEdit->setObjectName("dateEdit");
        dateEdit->setGeometry(QRect(90, 100, 121, 41));
        dateEdit_2 = new QDateEdit(DoanhThu4);
        dateEdit_2->setObjectName("dateEdit_2");
        dateEdit_2->setGeometry(QRect(330, 100, 121, 41));
        tableWidgetDSDoanhThu = new QTableWidget(DoanhThu4);
        if (tableWidgetDSDoanhThu->columnCount() < 8)
            tableWidgetDSDoanhThu->setColumnCount(8);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidgetDSDoanhThu->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidgetDSDoanhThu->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidgetDSDoanhThu->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidgetDSDoanhThu->setHorizontalHeaderItem(3, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWidgetDSDoanhThu->setHorizontalHeaderItem(4, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tableWidgetDSDoanhThu->setHorizontalHeaderItem(5, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tableWidgetDSDoanhThu->setHorizontalHeaderItem(6, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        tableWidgetDSDoanhThu->setHorizontalHeaderItem(7, __qtablewidgetitem7);
        tableWidgetDSDoanhThu->setObjectName("tableWidgetDSDoanhThu");
        tableWidgetDSDoanhThu->setGeometry(QRect(30, 220, 811, 291));
        QFont font12;
        font12.setPointSize(10);
        tableWidgetDSDoanhThu->setFont(font12);
        pushButton_6 = new QPushButton(DoanhThu4);
        pushButton_6->setObjectName("pushButton_6");
        pushButton_6->setGeometry(QRect(510, 100, 131, 36));
        stackedWidget->addWidget(DoanhThu4);
        DanhSachDoanhThu5 = new QWidget();
        DanhSachDoanhThu5->setObjectName("DanhSachDoanhThu5");
        label0_22 = new QLabel(DanhSachDoanhThu5);
        label0_22->setObjectName("label0_22");
        label0_22->setGeometry(QRect(360, 10, 141, 41));
        label0_22->setFont(font3);
        label0_22->setAutoFillBackground(false);
        pushButton_24 = new QPushButton(DanhSachDoanhThu5);
        pushButton_24->setObjectName("pushButton_24");
        pushButton_24->setGeometry(QRect(720, 0, 151, 40));
        pushButton_24->setFont(font6);
        pushButton_25 = new QPushButton(DanhSachDoanhThu5);
        pushButton_25->setObjectName("pushButton_25");
        pushButton_25->setGeometry(QRect(0, 0, 111, 41));
        stackedWidget->addWidget(DanhSachDoanhThu5);
        TimTheoDiaChi6 = new QWidget();
        TimTheoDiaChi6->setObjectName("TimTheoDiaChi6");
        label0_23 = new QLabel(TimTheoDiaChi6);
        label0_23->setObjectName("label0_23");
        label0_23->setGeometry(QRect(330, 0, 219, 39));
        label0_23->setFont(font3);
        label0_23->setAutoFillBackground(false);
        label0_24 = new QLabel(TimTheoDiaChi6);
        label0_24->setObjectName("label0_24");
        label0_24->setGeometry(QRect(30, 80, 101, 36));
        label0_24->setFont(font1);
        label0_24->setAutoFillBackground(false);
        textEdit_52 = new QTextEdit(TimTheoDiaChi6);
        textEdit_52->setObjectName("textEdit_52");
        textEdit_52->setGeometry(QRect(150, 70, 571, 41));
        textEdit_52->setFont(font11);
        pushButton_26 = new QPushButton(TimTheoDiaChi6);
        pushButton_26->setObjectName("pushButton_26");
        pushButton_26->setGeometry(QRect(720, 0, 151, 40));
        pushButton_26->setFont(font6);
        tableWidgetDSDiaChi = new QTableWidget(TimTheoDiaChi6);
        if (tableWidgetDSDiaChi->columnCount() < 8)
            tableWidgetDSDiaChi->setColumnCount(8);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        tableWidgetDSDiaChi->setHorizontalHeaderItem(0, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        tableWidgetDSDiaChi->setHorizontalHeaderItem(1, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        tableWidgetDSDiaChi->setHorizontalHeaderItem(2, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        tableWidgetDSDiaChi->setHorizontalHeaderItem(3, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        tableWidgetDSDiaChi->setHorizontalHeaderItem(4, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        tableWidgetDSDiaChi->setHorizontalHeaderItem(5, __qtablewidgetitem13);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        tableWidgetDSDiaChi->setHorizontalHeaderItem(6, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        tableWidgetDSDiaChi->setHorizontalHeaderItem(7, __qtablewidgetitem15);
        tableWidgetDSDiaChi->setObjectName("tableWidgetDSDiaChi");
        tableWidgetDSDiaChi->setGeometry(QRect(30, 140, 811, 371));
        tableWidgetDSDiaChi->setFont(font12);
        pushButton_7 = new QPushButton(TimTheoDiaChi6);
        pushButton_7->setObjectName("pushButton_7");
        pushButton_7->setGeometry(QRect(740, 70, 94, 41));
        stackedWidget->addWidget(TimTheoDiaChi6);
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName("menubar");
        menubar->setGeometry(QRect(0, 0, 886, 21));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName("statusbar");
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        label0->setText(QCoreApplication::translate("MainWindow", "Giao di\341\273\207n ch\303\255nh", nullptr));
        pushButton_1->setText(QString());
        pushButton_2->setText(QCoreApplication::translate("MainWindow", "Th\303\252m", nullptr));
        pushButton_3->setText(QCoreApplication::translate("MainWindow", "C\341\272\255p nh\341\272\255t gi\303\241", nullptr));
        pushButton_4->setText(QCoreApplication::translate("MainWindow", "T\303\254m theo \304\221\341\273\213a ch\341\273\211", nullptr));
        pushButton_5->setText(QCoreApplication::translate("MainWindow", "Doanh thu", nullptr));
        label0_2->setText(QCoreApplication::translate("MainWindow", "Th\303\252m", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "\304\220/c g\341\273\255i", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "\304\220/c nh\341\272\255n", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", " Ng\303\240y g\341\273\255i", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "Lo\341\272\241i \304\221\306\241n h\303\240ng", nullptr));
        radioButtonTaiLieu->setText(QCoreApplication::translate("MainWindow", "T\303\240i li\341\273\207u", nullptr));
        checkBoxDenChua->setText(QCoreApplication::translate("MainWindow", "\304\220\306\241n h\303\240ng \304\221\303\243 g\341\273\255i t\341\273\233i h\303\264m", nullptr));
        radioButton_2->setText(QCoreApplication::translate("MainWindow", "B\306\260u ki\341\273\207n", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "Qu\303\243ng \304\221\306\260\341\273\235ng", nullptr));
        label_8->setText(QCoreApplication::translate("MainWindow", "KG", nullptr));
        pushButton_23->setText(QCoreApplication::translate("MainWindow", "Giao di\341\273\207n ch\303\255nh", nullptr));
        pushButton->setText(QCoreApplication::translate("MainWindow", "X\303\241c nh\341\272\255n", nullptr));
        label_25->setText(QCoreApplication::translate("MainWindow", "T\303\252n ng\306\260\341\273\235i g\341\273\255i", nullptr));
        label_26->setText(QCoreApplication::translate("MainWindow", "T\303\252n Ng\306\260\341\273\235i Nh\341\272\255n", nullptr));
        label0_3->setText(QCoreApplication::translate("MainWindow", "\304\220\306\241n h\303\240ng \304\221\303\243 \304\221\306\260\341\273\243c th\303\252m th\303\240nh c\303\264ng", nullptr));
        label0_4->setText(QCoreApplication::translate("MainWindow", "M\303\243 v\341\272\255n \304\221\306\241n l\303\240 :", nullptr));
        label0_5->setText(QCoreApplication::translate("MainWindow", "Th\303\264ng tin :", nullptr));
        label_28->setText(QCoreApplication::translate("MainWindow", "T\303\252n ng\306\260\341\273\235i g\341\273\255i", nullptr));
        label_27->setText(QCoreApplication::translate("MainWindow", "T\303\252n ng\306\260\341\273\235i nh\341\272\255n", nullptr));
        label_11->setText(QCoreApplication::translate("MainWindow", "\304\220/c g\341\273\255i", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindow", "\304\220/c nh\341\272\255n", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "Qu\303\243ng \304\221\306\260\341\273\235ng", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindow", "Ng\303\240y", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "Lo\341\272\241i \304\221\306\241n h\303\240ng", nullptr));
        label_16->setText(QCoreApplication::translate("MainWindow", "\304\220\306\241n h\303\240ng \304\221\303\243 g\341\273\255i t\341\273\233i h\303\264m", nullptr));
        pushButton_18->setText(QCoreApplication::translate("MainWindow", "Ch\341\273\211nh s\341\273\255a", nullptr));
        pushButton_20->setText(QCoreApplication::translate("MainWindow", "Giao di\341\273\207n ch\303\255nh", nullptr));
        labelID->setText(QString());
        labelDiaChiGui->setText(QString());
        labelDiaChiNhan->setText(QString());
        labelQuangDuong->setText(QString());
        labelTaiLieuHayBuuKien->setText(QString());
        labelNgayThangNamGui->setText(QString());
        labelNgayThangNamNhan->setText(QString());
        labelTenNguoiGui->setText(QString());
        labelTenNguoiNhan->setText(QString());
        label0_11->setText(QCoreApplication::translate("MainWindow", "C\341\272\255p nh\341\272\255t gi\303\241", nullptr));
        checkBox_5->setText(QCoreApplication::translate("MainWindow", "T\303\240i li\341\273\207u", nullptr));
        checkBox_6->setText(QCoreApplication::translate("MainWindow", "B\306\260u ki\341\273\207n", nullptr));
        label_35->setText(QCoreApplication::translate("MainWindow", "Gi\303\241 nh\341\272\255n \304\221\306\241n :", nullptr));
        label_36->setText(QCoreApplication::translate("MainWindow", "Gi\303\241 Kilometer :", nullptr));
        label_37->setText(QCoreApplication::translate("MainWindow", "Gi\303\241 c\303\242n n\341\272\267ng :", nullptr));
        label_38->setText(QCoreApplication::translate("MainWindow", "Gi\303\241 Kilometer :", nullptr));
        label0_12->setText(QCoreApplication::translate("MainWindow", "-->", nullptr));
        label0_13->setText(QCoreApplication::translate("MainWindow", "-->", nullptr));
        label0_14->setText(QCoreApplication::translate("MainWindow", "-->", nullptr));
        label0_15->setText(QCoreApplication::translate("MainWindow", "-->", nullptr));
        pushButton_13->setText(QCoreApplication::translate("MainWindow", "\304\220\341\272\267t v\341\273\201 m\341\272\267c \304\221\341\273\213nh", nullptr));
        pushButton_15->setText(QCoreApplication::translate("MainWindow", "L\306\260u", nullptr));
        pushButton_22->setText(QCoreApplication::translate("MainWindow", "Giao di\341\273\207n ch\303\255nh", nullptr));
        label_51->setText(QString());
        label_52->setText(QString());
        label_53->setText(QString());
        label_54->setText(QString());
        label0_16->setText(QCoreApplication::translate("MainWindow", "Doanh thu", nullptr));
        label0_17->setText(QCoreApplication::translate("MainWindow", "Kho\341\272\243ng th\341\273\235i gian :", nullptr));
        label0_18->setText(QCoreApplication::translate("MainWindow", "Doanh thu :", nullptr));
        label0_19->setText(QCoreApplication::translate("MainWindow", "\304\220\341\273\223ng", nullptr));
        label0_20->setText(QCoreApplication::translate("MainWindow", "T\341\273\253 : ", nullptr));
        label0_21->setText(QCoreApplication::translate("MainWindow", "\304\220\341\272\277n : ", nullptr));
        pushButton_21->setText(QCoreApplication::translate("MainWindow", "Giao di\341\273\207n ch\303\255nh", nullptr));
        label_6->setText(QString());
        QTableWidgetItem *___qtablewidgetitem = tableWidgetDSDoanhThu->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("MainWindow", "T\303\252n ng\306\260\341\273\235i g\341\273\255i", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidgetDSDoanhThu->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("MainWindow", "\304\220\341\273\213a ch\341\273\211 g\341\273\255i", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidgetDSDoanhThu->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("MainWindow", "T\303\252n ng\306\260\341\273\235i nh\341\272\255n", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidgetDSDoanhThu->horizontalHeaderItem(3);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("MainWindow", "\304\220\341\273\213a ch\341\273\211 nh\341\272\255n", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidgetDSDoanhThu->horizontalHeaderItem(4);
        ___qtablewidgetitem4->setText(QCoreApplication::translate("MainWindow", "Ng\303\240y nh\341\272\255n", nullptr));
        QTableWidgetItem *___qtablewidgetitem5 = tableWidgetDSDoanhThu->horizontalHeaderItem(5);
        ___qtablewidgetitem5->setText(QCoreApplication::translate("MainWindow", "Ng\303\240y g\341\273\255i", nullptr));
        QTableWidgetItem *___qtablewidgetitem6 = tableWidgetDSDoanhThu->horizontalHeaderItem(6);
        ___qtablewidgetitem6->setText(QCoreApplication::translate("MainWindow", "Lo\341\272\241i \304\221\306\241n h\303\240ng", nullptr));
        QTableWidgetItem *___qtablewidgetitem7 = tableWidgetDSDoanhThu->horizontalHeaderItem(7);
        ___qtablewidgetitem7->setText(QCoreApplication::translate("MainWindow", "Thu \304\221\306\260\341\273\243c", nullptr));
        pushButton_6->setText(QCoreApplication::translate("MainWindow", "X\303\241c nh\341\272\255n", nullptr));
        label0_22->setText(QCoreApplication::translate("MainWindow", "Th\341\273\221ng k\303\252", nullptr));
        pushButton_24->setText(QCoreApplication::translate("MainWindow", "Giao di\341\273\207n ch\303\255nh", nullptr));
        pushButton_25->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        label0_23->setText(QCoreApplication::translate("MainWindow", "T\303\254m theo \304\221\341\273\213a ch\341\273\211", nullptr));
        label0_24->setText(QCoreApplication::translate("MainWindow", "\304\220\341\273\213a ch\341\273\211 :", nullptr));
        pushButton_26->setText(QCoreApplication::translate("MainWindow", "Giao di\341\273\207n ch\303\255nh", nullptr));
        QTableWidgetItem *___qtablewidgetitem8 = tableWidgetDSDiaChi->horizontalHeaderItem(0);
        ___qtablewidgetitem8->setText(QCoreApplication::translate("MainWindow", "T\303\252n ng\306\260\341\273\235i g\341\273\255i", nullptr));
        QTableWidgetItem *___qtablewidgetitem9 = tableWidgetDSDiaChi->horizontalHeaderItem(1);
        ___qtablewidgetitem9->setText(QCoreApplication::translate("MainWindow", "\304\220\341\273\213a ch\341\273\211 g\341\273\255i", nullptr));
        QTableWidgetItem *___qtablewidgetitem10 = tableWidgetDSDiaChi->horizontalHeaderItem(2);
        ___qtablewidgetitem10->setText(QCoreApplication::translate("MainWindow", "T\303\252n ng\306\260\341\273\235i nh\341\272\255n", nullptr));
        QTableWidgetItem *___qtablewidgetitem11 = tableWidgetDSDiaChi->horizontalHeaderItem(3);
        ___qtablewidgetitem11->setText(QCoreApplication::translate("MainWindow", "\304\220\341\273\213a ch\341\273\211 nh\341\272\255n", nullptr));
        QTableWidgetItem *___qtablewidgetitem12 = tableWidgetDSDiaChi->horizontalHeaderItem(4);
        ___qtablewidgetitem12->setText(QCoreApplication::translate("MainWindow", "Ng\303\240y nh\341\272\255n", nullptr));
        QTableWidgetItem *___qtablewidgetitem13 = tableWidgetDSDiaChi->horizontalHeaderItem(5);
        ___qtablewidgetitem13->setText(QCoreApplication::translate("MainWindow", "Ng\303\240y g\341\273\255i", nullptr));
        QTableWidgetItem *___qtablewidgetitem14 = tableWidgetDSDiaChi->horizontalHeaderItem(6);
        ___qtablewidgetitem14->setText(QCoreApplication::translate("MainWindow", "Lo\341\272\241i \304\221\306\241n h\303\240ng", nullptr));
        QTableWidgetItem *___qtablewidgetitem15 = tableWidgetDSDiaChi->horizontalHeaderItem(7);
        ___qtablewidgetitem15->setText(QCoreApplication::translate("MainWindow", "Thu \304\221\306\260\341\273\243c", nullptr));
        pushButton_7->setText(QCoreApplication::translate("MainWindow", "X\303\241c nh\341\272\255n", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
