/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.4.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDateEdit>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QStackedWidget *stackedWidget;
    QWidget *GiaoDienChinh0;
    QLabel *label0;
    QPushButton *pushButton_1;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QPushButton *pushButtonThongKe;
    QPushButton *pushButtonGiaoDienXoaDon;
    QPushButton *pushButtonGiaoDienChinhSuaDon;
    QWidget *Them1;
    QLabel *label0_2;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QRadioButton *radioButtonTaiLieu;
    QTextEdit *textEditDiaChiGui;
    QCheckBox *checkBoxDenChua;
    QRadioButton *radioButtonBuuKien;
    QTextEdit *textEditDiaChiNhan;
    QLabel *label_5;
    QLabel *label_8;
    QPushButton *pushButton_23;
    QPushButton *pushButtonXacNhanThemDon;
    QDateEdit *dateEditNgayGui;
    QLabel *label_25;
    QTextEdit *textEditTenNguoiGui;
    QLabel *label_26;
    QTextEdit *textEditTenNguoiNhan;
    QDateEdit *dateEditNgayNhan;
    QDoubleSpinBox *doubleSpinBoxQuangDuong;
    QDoubleSpinBox *doubleSpinBoxCanNang;
    QWidget *ThemThanhCong3;
    QLabel *label0_3;
    QLabel *label0_4;
    QLabel *label0_5;
    QWidget *verticalLayoutWidget;
    QVBoxLayout *verticalLayout;
    QLabel *label_28;
    QLabel *label_27;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_15;
    QLabel *label_14;
    QLabel *label_13;
    QLabel *label_16;
    QPushButton *pushButton_18;
    QPushButton *pushButton_20;
    QLabel *labelID;
    QWidget *layoutWidget;
    QVBoxLayout *verticalLayout_2;
    QLabel *labelTenNguoiGui;
    QLabel *labelTenNguoiNhan;
    QLabel *labelDiaChiGui;
    QLabel *labelDiaChiNhan;
    QLabel *labelQuangDuong;
    QLabel *labelNgayThangNamGui;
    QLabel *labelTaiLieuHayBuuKien;
    QLabel *labelNgayThangNamNhan;
    QWidget *CapNhatGia3;
    QLabel *label0_11;
    QCheckBox *checkBoxTaiLieu;
    QCheckBox *checkBoxBuuKien;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label0_12;
    QLabel *label0_13;
    QLabel *label0_14;
    QLabel *label0_15;
    QTextEdit *textEditGiaNhanDonTaiLieu;
    QTextEdit *textEditGiaQuangDuongTaiLieu;
    QTextEdit *textEditGiaCanNangBuuKien;
    QTextEdit *textEditGiaQuangDuongBuuKien;
    QPushButton *pushButtonDatVeMacDinh;
    QPushButton *pushButtonCapNhatGia;
    QPushButton *pushButton_22;
    QLabel *labelGiaNhanDonTaiLieu;
    QLabel *labelGiaQuangDuongTaiLieu;
    QLabel *labelGiaCanNangBuuKien;
    QLabel *labelGiaQuangDuongBuuKien;
    QWidget *DoanhThu4;
    QLabel *label0_16;
    QLabel *label0_17;
    QLabel *label0_18;
    QLabel *label0_19;
    QLabel *label0_20;
    QLabel *label0_21;
    QPushButton *pushButton_21;
    QLabel *label_6;
    QDateEdit *dateEdit;
    QDateEdit *dateEdit_2;
    QTableWidget *tableWidgetDSDoanhThu;
    QPushButton *pushButtonXacNhanThongKeTheoThoiGian;
    QWidget *DanhSachDoanhThu5;
    QPushButton *pushButton_25;
    QLabel *label0_6;
    QSpinBox *spinBoxSTTCanChinhSua;
    QPushButton *pushButtonXacNhanChonDonChinhSua;
    QTableWidget *tableWidgetDSToanBoDonHangGiaoDienChinhSua;
    QLabel *label0_43;
    QWidget *TimTheoDiaChi6;
    QLabel *label0_23;
    QLabel *label0_24;
    QTextEdit *textSearch;
    QPushButton *pushButton_26;
    QTableWidget *tableWidgetDSDiaChi;
    QPushButton *pushButton_7;
    QWidget *page;
    QLabel *label0_25;
    QLabel *label0_26;
    QTableWidget *tableWidgetDSToanBoDonHang;
    QPushButton *pushButtonXacNhanXoaDon;
    QPushButton *pushButton_24;
    QSpinBox *spinBoxSTTCanXoa;
    QWidget *page_2;
    QPushButton *pushButtonXacNhanThemDon_2;
    QLabel *label_7;
    QCheckBox *checkBoxDenChua_2;
    QLabel *label_9;
    QTextEdit *textEditTenNguoiNhan_2;
    QLabel *label_10;
    QDoubleSpinBox *doubleSpinBoxCanNang_2;
    QLabel *label_29;
    QDoubleSpinBox *doubleSpinBoxQuangDuong_2;
    QRadioButton *radioButtonBuuKien_2;
    QLabel *label0_7;
    QLabel *label_17;
    QDateEdit *dateEditNgayGui_2;
    QLabel *label_30;
    QDateEdit *dateEditNgayNhan_2;
    QTextEdit *textEditDiaChiGui_2;
    QPushButton *pushButton_27;
    QTextEdit *textEditDiaChiNhan_2;
    QLabel *label_18;
    QTextEdit *textEditTenNguoiGui_2;
    QLabel *label_19;
    QRadioButton *radioButtonTaiLieu_2;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName("MainWindow");
        MainWindow->resize(904, 574);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName("centralwidget");
        stackedWidget = new QStackedWidget(centralwidget);
        stackedWidget->setObjectName("stackedWidget");
        stackedWidget->setGeometry(QRect(10, 10, 871, 531));
        QFont font;
        font.setPointSize(16);
        stackedWidget->setFont(font);
        stackedWidget->setAutoFillBackground(false);
        GiaoDienChinh0 = new QWidget();
        GiaoDienChinh0->setObjectName("GiaoDienChinh0");
        label0 = new QLabel(GiaoDienChinh0);
        label0->setObjectName("label0");
        label0->setGeometry(QRect(330, 75, 198, 51));
        QFont font1;
        font1.setFamilies({QString::fromUtf8("Segoe UI")});
        font1.setPointSize(20);
        font1.setBold(true);
        label0->setFont(font1);
        pushButton_1 = new QPushButton(GiaoDienChinh0);
        pushButton_1->setObjectName("pushButton_1");
        pushButton_1->setGeometry(QRect(100, 60, 671, 81));
        QFont font2;
        font2.setFamilies({QString::fromUtf8("Segoe UI")});
        font2.setPointSize(18);
        font2.setBold(true);
        pushButton_1->setFont(font2);
        pushButton_2 = new QPushButton(GiaoDienChinh0);
        pushButton_2->setObjectName("pushButton_2");
        pushButton_2->setGeometry(QRect(500, 210, 101, 91));
        pushButton_2->setFont(font2);
        pushButton_3 = new QPushButton(GiaoDienChinh0);
        pushButton_3->setObjectName("pushButton_3");
        pushButton_3->setGeometry(QRect(60, 360, 301, 101));
        pushButton_3->setFont(font2);
        pushButton_4 = new QPushButton(GiaoDienChinh0);
        pushButton_4->setObjectName("pushButton_4");
        pushButton_4->setGeometry(QRect(60, 210, 301, 91));
        pushButton_4->setFont(font2);
        pushButtonThongKe = new QPushButton(GiaoDienChinh0);
        pushButtonThongKe->setObjectName("pushButtonThongKe");
        pushButtonThongKe->setGeometry(QRect(500, 360, 311, 101));
        pushButtonThongKe->setFont(font2);
        pushButtonGiaoDienXoaDon = new QPushButton(GiaoDienChinh0);
        pushButtonGiaoDienXoaDon->setObjectName("pushButtonGiaoDienXoaDon");
        pushButtonGiaoDienXoaDon->setGeometry(QRect(610, 210, 101, 91));
        pushButtonGiaoDienXoaDon->setFont(font2);
        pushButtonGiaoDienChinhSuaDon = new QPushButton(GiaoDienChinh0);
        pushButtonGiaoDienChinhSuaDon->setObjectName("pushButtonGiaoDienChinhSuaDon");
        pushButtonGiaoDienChinhSuaDon->setGeometry(QRect(720, 210, 91, 91));
        QFont font3;
        font3.setPointSize(18);
        font3.setBold(true);
        pushButtonGiaoDienChinhSuaDon->setFont(font3);
        stackedWidget->addWidget(GiaoDienChinh0);
        pushButton_1->raise();
        label0->raise();
        pushButton_2->raise();
        pushButton_3->raise();
        pushButton_4->raise();
        pushButtonThongKe->raise();
        pushButtonGiaoDienXoaDon->raise();
        pushButtonGiaoDienChinhSuaDon->raise();
        Them1 = new QWidget();
        Them1->setObjectName("Them1");
        label0_2 = new QLabel(Them1);
        label0_2->setObjectName("label0_2");
        label0_2->setGeometry(QRect(430, 0, 81, 41));
        QFont font4;
        font4.setFamilies({QString::fromUtf8("Segoe UI")});
        font4.setPointSize(22);
        font4.setBold(true);
        label0_2->setFont(font4);
        label0_2->setAutoFillBackground(false);
        label = new QLabel(Them1);
        label->setObjectName("label");
        label->setGeometry(QRect(20, 191, 73, 28));
        QFont font5;
        font5.setPointSize(16);
        font5.setBold(true);
        label->setFont(font5);
        label_2 = new QLabel(Them1);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(20, 260, 90, 28));
        label_2->setFont(font5);
        label_3 = new QLabel(Them1);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(20, 410, 97, 28));
        label_3->setFont(font5);
        label_4 = new QLabel(Them1);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(20, 310, 142, 28));
        label_4->setFont(font5);
        radioButtonTaiLieu = new QRadioButton(Them1);
        radioButtonTaiLieu->setObjectName("radioButtonTaiLieu");
        radioButtonTaiLieu->setGeometry(QRect(180, 310, 94, 34));
        radioButtonTaiLieu->setFont(font5);
        textEditDiaChiGui = new QTextEdit(Them1);
        textEditDiaChiGui->setObjectName("textEditDiaChiGui");
        textEditDiaChiGui->setGeometry(QRect(120, 180, 461, 41));
        QFont font6;
        font6.setPointSize(14);
        textEditDiaChiGui->setFont(font6);
        checkBoxDenChua = new QCheckBox(Them1);
        checkBoxDenChua->setObjectName("checkBoxDenChua");
        checkBoxDenChua->setGeometry(QRect(440, 410, 275, 34));
        checkBoxDenChua->setFont(font5);
        radioButtonBuuKien = new QRadioButton(Them1);
        radioButtonBuuKien->setObjectName("radioButtonBuuKien");
        radioButtonBuuKien->setGeometry(QRect(180, 350, 113, 34));
        radioButtonBuuKien->setFont(font5);
        textEditDiaChiNhan = new QTextEdit(Them1);
        textEditDiaChiNhan->setObjectName("textEditDiaChiNhan");
        textEditDiaChiNhan->setGeometry(QRect(120, 250, 461, 41));
        textEditDiaChiNhan->setFont(font6);
        label_5 = new QLabel(Them1);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(680, 210, 138, 28));
        label_5->setFont(font5);
        label_8 = new QLabel(Them1);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(480, 350, 52, 28));
        label_8->setFont(font5);
        pushButton_23 = new QPushButton(Them1);
        pushButton_23->setObjectName("pushButton_23");
        pushButton_23->setGeometry(QRect(720, 0, 151, 40));
        QFont font7;
        font7.setPointSize(11);
        font7.setBold(false);
        pushButton_23->setFont(font7);
        pushButtonXacNhanThemDon = new QPushButton(Them1);
        pushButtonXacNhanThemDon->setObjectName("pushButtonXacNhanThemDon");
        pushButtonXacNhanThemDon->setGeometry(QRect(370, 470, 151, 41));
        QFont font8;
        font8.setPointSize(11);
        pushButtonXacNhanThemDon->setFont(font8);
        dateEditNgayGui = new QDateEdit(Them1);
        dateEditNgayGui->setObjectName("dateEditNgayGui");
        dateEditNgayGui->setGeometry(QRect(130, 410, 111, 31));
        dateEditNgayGui->setFont(font8);
        label_25 = new QLabel(Them1);
        label_25->setObjectName("label_25");
        label_25->setGeometry(QRect(20, 70, 138, 28));
        label_25->setFont(font5);
        textEditTenNguoiGui = new QTextEdit(Them1);
        textEditTenNguoiGui->setObjectName("textEditTenNguoiGui");
        textEditTenNguoiGui->setGeometry(QRect(170, 60, 481, 41));
        textEditTenNguoiGui->setFont(font6);
        label_26 = new QLabel(Them1);
        label_26->setObjectName("label_26");
        label_26->setGeometry(QRect(20, 130, 163, 28));
        label_26->setFont(font5);
        textEditTenNguoiNhan = new QTextEdit(Them1);
        textEditTenNguoiNhan->setObjectName("textEditTenNguoiNhan");
        textEditTenNguoiNhan->setGeometry(QRect(190, 119, 461, 41));
        textEditTenNguoiNhan->setFont(font6);
        dateEditNgayNhan = new QDateEdit(Them1);
        dateEditNgayNhan->setObjectName("dateEditNgayNhan");
        dateEditNgayNhan->setGeometry(QRect(720, 410, 111, 31));
        dateEditNgayNhan->setFont(font8);
        doubleSpinBoxQuangDuong = new QDoubleSpinBox(Them1);
        doubleSpinBoxQuangDuong->setObjectName("doubleSpinBoxQuangDuong");
        doubleSpinBoxQuangDuong->setGeometry(QRect(670, 250, 161, 41));
        doubleSpinBoxCanNang = new QDoubleSpinBox(Them1);
        doubleSpinBoxCanNang->setObjectName("doubleSpinBoxCanNang");
        doubleSpinBoxCanNang->setGeometry(QRect(300, 340, 161, 41));
        stackedWidget->addWidget(Them1);
        ThemThanhCong3 = new QWidget();
        ThemThanhCong3->setObjectName("ThemThanhCong3");
        label0_3 = new QLabel(ThemThanhCong3);
        label0_3->setObjectName("label0_3");
        label0_3->setGeometry(QRect(200, 20, 495, 39));
        label0_3->setFont(font4);
        label0_3->setAutoFillBackground(false);
        label0_4 = new QLabel(ThemThanhCong3);
        label0_4->setObjectName("label0_4");
        label0_4->setGeometry(QRect(260, 80, 212, 39));
        label0_4->setFont(font4);
        label0_4->setAutoFillBackground(false);
        label0_5 = new QLabel(ThemThanhCong3);
        label0_5->setObjectName("label0_5");
        label0_5->setGeometry(QRect(60, 140, 97, 26));
        QFont font9;
        font9.setFamilies({QString::fromUtf8("Segoe UI")});
        font9.setPointSize(16);
        font9.setBold(true);
        label0_5->setFont(font9);
        label0_5->setAutoFillBackground(false);
        verticalLayoutWidget = new QWidget(ThemThanhCong3);
        verticalLayoutWidget->setObjectName("verticalLayoutWidget");
        verticalLayoutWidget->setGeometry(QRect(180, 130, 323, 382));
        verticalLayout = new QVBoxLayout(verticalLayoutWidget);
        verticalLayout->setObjectName("verticalLayout");
        verticalLayout->setContentsMargins(0, 0, 0, 0);
        label_28 = new QLabel(verticalLayoutWidget);
        label_28->setObjectName("label_28");
        label_28->setFont(font5);

        verticalLayout->addWidget(label_28);

        label_27 = new QLabel(verticalLayoutWidget);
        label_27->setObjectName("label_27");
        label_27->setFont(font5);

        verticalLayout->addWidget(label_27);

        label_11 = new QLabel(verticalLayoutWidget);
        label_11->setObjectName("label_11");
        label_11->setFont(font5);

        verticalLayout->addWidget(label_11);

        label_12 = new QLabel(verticalLayoutWidget);
        label_12->setObjectName("label_12");
        label_12->setFont(font5);

        verticalLayout->addWidget(label_12);

        label_15 = new QLabel(verticalLayoutWidget);
        label_15->setObjectName("label_15");
        label_15->setFont(font5);

        verticalLayout->addWidget(label_15);

        label_14 = new QLabel(verticalLayoutWidget);
        label_14->setObjectName("label_14");
        label_14->setFont(font5);

        verticalLayout->addWidget(label_14);

        label_13 = new QLabel(verticalLayoutWidget);
        label_13->setObjectName("label_13");
        label_13->setFont(font5);

        verticalLayout->addWidget(label_13);

        label_16 = new QLabel(verticalLayoutWidget);
        label_16->setObjectName("label_16");
        label_16->setFont(font5);

        verticalLayout->addWidget(label_16);

        pushButton_18 = new QPushButton(ThemThanhCong3);
        pushButton_18->setObjectName("pushButton_18");
        pushButton_18->setGeometry(QRect(40, 200, 120, 40));
        pushButton_18->setFont(font3);
        pushButton_20 = new QPushButton(ThemThanhCong3);
        pushButton_20->setObjectName("pushButton_20");
        pushButton_20->setGeometry(QRect(720, 0, 151, 40));
        pushButton_20->setFont(font7);
        labelID = new QLabel(ThemThanhCong3);
        labelID->setObjectName("labelID");
        labelID->setGeometry(QRect(490, 80, 201, 41));
        labelID->setFont(font4);
        labelID->setAutoFillBackground(false);
        layoutWidget = new QWidget(ThemThanhCong3);
        layoutWidget->setObjectName("layoutWidget");
        layoutWidget->setGeometry(QRect(510, 130, 351, 381));
        verticalLayout_2 = new QVBoxLayout(layoutWidget);
        verticalLayout_2->setObjectName("verticalLayout_2");
        verticalLayout_2->setContentsMargins(0, 0, 0, 0);
        labelTenNguoiGui = new QLabel(layoutWidget);
        labelTenNguoiGui->setObjectName("labelTenNguoiGui");
        labelTenNguoiGui->setFont(font9);
        labelTenNguoiGui->setMouseTracking(false);
        labelTenNguoiGui->setTabletTracking(false);
        labelTenNguoiGui->setAutoFillBackground(false);

        verticalLayout_2->addWidget(labelTenNguoiGui);

        labelTenNguoiNhan = new QLabel(layoutWidget);
        labelTenNguoiNhan->setObjectName("labelTenNguoiNhan");
        labelTenNguoiNhan->setFont(font9);
        labelTenNguoiNhan->setMouseTracking(false);
        labelTenNguoiNhan->setTabletTracking(false);
        labelTenNguoiNhan->setAutoFillBackground(false);

        verticalLayout_2->addWidget(labelTenNguoiNhan);

        labelDiaChiGui = new QLabel(layoutWidget);
        labelDiaChiGui->setObjectName("labelDiaChiGui");
        labelDiaChiGui->setFont(font9);
        labelDiaChiGui->setMouseTracking(false);
        labelDiaChiGui->setTabletTracking(false);
        labelDiaChiGui->setAutoFillBackground(false);

        verticalLayout_2->addWidget(labelDiaChiGui);

        labelDiaChiNhan = new QLabel(layoutWidget);
        labelDiaChiNhan->setObjectName("labelDiaChiNhan");
        labelDiaChiNhan->setFont(font9);
        labelDiaChiNhan->setMouseTracking(false);
        labelDiaChiNhan->setTabletTracking(false);
        labelDiaChiNhan->setAutoFillBackground(false);

        verticalLayout_2->addWidget(labelDiaChiNhan);

        labelQuangDuong = new QLabel(layoutWidget);
        labelQuangDuong->setObjectName("labelQuangDuong");
        labelQuangDuong->setFont(font9);
        labelQuangDuong->setMouseTracking(false);
        labelQuangDuong->setTabletTracking(false);
        labelQuangDuong->setAutoFillBackground(false);

        verticalLayout_2->addWidget(labelQuangDuong);

        labelNgayThangNamGui = new QLabel(layoutWidget);
        labelNgayThangNamGui->setObjectName("labelNgayThangNamGui");
        labelNgayThangNamGui->setFont(font9);
        labelNgayThangNamGui->setMouseTracking(false);
        labelNgayThangNamGui->setTabletTracking(false);
        labelNgayThangNamGui->setAutoFillBackground(false);

        verticalLayout_2->addWidget(labelNgayThangNamGui);

        labelTaiLieuHayBuuKien = new QLabel(layoutWidget);
        labelTaiLieuHayBuuKien->setObjectName("labelTaiLieuHayBuuKien");
        labelTaiLieuHayBuuKien->setFont(font9);
        labelTaiLieuHayBuuKien->setMouseTracking(false);
        labelTaiLieuHayBuuKien->setTabletTracking(false);
        labelTaiLieuHayBuuKien->setAutoFillBackground(false);

        verticalLayout_2->addWidget(labelTaiLieuHayBuuKien);

        labelNgayThangNamNhan = new QLabel(layoutWidget);
        labelNgayThangNamNhan->setObjectName("labelNgayThangNamNhan");
        labelNgayThangNamNhan->setFont(font9);
        labelNgayThangNamNhan->setMouseTracking(false);
        labelNgayThangNamNhan->setTabletTracking(false);
        labelNgayThangNamNhan->setAutoFillBackground(false);

        verticalLayout_2->addWidget(labelNgayThangNamNhan);

        stackedWidget->addWidget(ThemThanhCong3);
        CapNhatGia3 = new QWidget();
        CapNhatGia3->setObjectName("CapNhatGia3");
        label0_11 = new QLabel(CapNhatGia3);
        label0_11->setObjectName("label0_11");
        label0_11->setGeometry(QRect(330, 0, 172, 39));
        label0_11->setFont(font4);
        label0_11->setAutoFillBackground(false);
        checkBoxTaiLieu = new QCheckBox(CapNhatGia3);
        checkBoxTaiLieu->setObjectName("checkBoxTaiLieu");
        checkBoxTaiLieu->setGeometry(QRect(90, 70, 94, 34));
        checkBoxTaiLieu->setFont(font5);
        checkBoxBuuKien = new QCheckBox(CapNhatGia3);
        checkBoxBuuKien->setObjectName("checkBoxBuuKien");
        checkBoxBuuKien->setGeometry(QRect(90, 230, 279, 34));
        checkBoxBuuKien->setFont(font5);
        label_35 = new QLabel(CapNhatGia3);
        label_35->setObjectName("label_35");
        label_35->setGeometry(QRect(110, 130, 130, 26));
        QFont font10;
        font10.setPointSize(14);
        font10.setBold(true);
        label_35->setFont(font10);
        label_36 = new QLabel(CapNhatGia3);
        label_36->setObjectName("label_36");
        label_36->setGeometry(QRect(110, 180, 130, 26));
        label_36->setFont(font10);
        label_37 = new QLabel(CapNhatGia3);
        label_37->setObjectName("label_37");
        label_37->setGeometry(QRect(110, 290, 130, 26));
        label_37->setFont(font10);
        label_38 = new QLabel(CapNhatGia3);
        label_38->setObjectName("label_38");
        label_38->setGeometry(QRect(110, 350, 130, 26));
        label_38->setFont(font10);
        label0_12 = new QLabel(CapNhatGia3);
        label0_12->setObjectName("label0_12");
        label0_12->setGeometry(QRect(440, 120, 45, 39));
        label0_12->setFont(font4);
        label0_12->setAutoFillBackground(false);
        label0_13 = new QLabel(CapNhatGia3);
        label0_13->setObjectName("label0_13");
        label0_13->setGeometry(QRect(440, 180, 45, 39));
        label0_13->setFont(font4);
        label0_13->setAutoFillBackground(false);
        label0_14 = new QLabel(CapNhatGia3);
        label0_14->setObjectName("label0_14");
        label0_14->setGeometry(QRect(440, 280, 45, 39));
        label0_14->setFont(font4);
        label0_14->setAutoFillBackground(false);
        label0_15 = new QLabel(CapNhatGia3);
        label0_15->setObjectName("label0_15");
        label0_15->setGeometry(QRect(440, 340, 45, 39));
        label0_15->setFont(font4);
        label0_15->setAutoFillBackground(false);
        textEditGiaNhanDonTaiLieu = new QTextEdit(CapNhatGia3);
        textEditGiaNhanDonTaiLieu->setObjectName("textEditGiaNhanDonTaiLieu");
        textEditGiaNhanDonTaiLieu->setGeometry(QRect(500, 120, 151, 41));
        QFont font11;
        font11.setPointSize(12);
        textEditGiaNhanDonTaiLieu->setFont(font11);
        textEditGiaQuangDuongTaiLieu = new QTextEdit(CapNhatGia3);
        textEditGiaQuangDuongTaiLieu->setObjectName("textEditGiaQuangDuongTaiLieu");
        textEditGiaQuangDuongTaiLieu->setGeometry(QRect(500, 180, 151, 41));
        textEditGiaQuangDuongTaiLieu->setFont(font11);
        textEditGiaCanNangBuuKien = new QTextEdit(CapNhatGia3);
        textEditGiaCanNangBuuKien->setObjectName("textEditGiaCanNangBuuKien");
        textEditGiaCanNangBuuKien->setGeometry(QRect(500, 280, 151, 41));
        textEditGiaCanNangBuuKien->setFont(font11);
        textEditGiaQuangDuongBuuKien = new QTextEdit(CapNhatGia3);
        textEditGiaQuangDuongBuuKien->setObjectName("textEditGiaQuangDuongBuuKien");
        textEditGiaQuangDuongBuuKien->setGeometry(QRect(500, 340, 151, 41));
        textEditGiaQuangDuongBuuKien->setFont(font11);
        pushButtonDatVeMacDinh = new QPushButton(CapNhatGia3);
        pushButtonDatVeMacDinh->setObjectName("pushButtonDatVeMacDinh");
        pushButtonDatVeMacDinh->setGeometry(QRect(260, 420, 215, 44));
        pushButtonDatVeMacDinh->setFont(font3);
        pushButtonCapNhatGia = new QPushButton(CapNhatGia3);
        pushButtonCapNhatGia->setObjectName("pushButtonCapNhatGia");
        pushButtonCapNhatGia->setGeometry(QRect(500, 420, 81, 41));
        pushButtonCapNhatGia->setFont(font3);
        pushButton_22 = new QPushButton(CapNhatGia3);
        pushButton_22->setObjectName("pushButton_22");
        pushButton_22->setGeometry(QRect(720, 0, 151, 40));
        pushButton_22->setFont(font7);
        labelGiaNhanDonTaiLieu = new QLabel(CapNhatGia3);
        labelGiaNhanDonTaiLieu->setObjectName("labelGiaNhanDonTaiLieu");
        labelGiaNhanDonTaiLieu->setGeometry(QRect(294, 130, 131, 28));
        labelGiaNhanDonTaiLieu->setFont(font3);
        labelGiaNhanDonTaiLieu->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelGiaQuangDuongTaiLieu = new QLabel(CapNhatGia3);
        labelGiaQuangDuongTaiLieu->setObjectName("labelGiaQuangDuongTaiLieu");
        labelGiaQuangDuongTaiLieu->setGeometry(QRect(294, 190, 131, 28));
        labelGiaQuangDuongTaiLieu->setFont(font3);
        labelGiaQuangDuongTaiLieu->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelGiaCanNangBuuKien = new QLabel(CapNhatGia3);
        labelGiaCanNangBuuKien->setObjectName("labelGiaCanNangBuuKien");
        labelGiaCanNangBuuKien->setGeometry(QRect(294, 290, 131, 28));
        labelGiaCanNangBuuKien->setFont(font3);
        labelGiaCanNangBuuKien->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        labelGiaQuangDuongBuuKien = new QLabel(CapNhatGia3);
        labelGiaQuangDuongBuuKien->setObjectName("labelGiaQuangDuongBuuKien");
        labelGiaQuangDuongBuuKien->setGeometry(QRect(294, 350, 131, 28));
        labelGiaQuangDuongBuuKien->setFont(font3);
        labelGiaQuangDuongBuuKien->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        stackedWidget->addWidget(CapNhatGia3);
        DoanhThu4 = new QWidget();
        DoanhThu4->setObjectName("DoanhThu4");
        label0_16 = new QLabel(DoanhThu4);
        label0_16->setObjectName("label0_16");
        label0_16->setGeometry(QRect(180, 0, 508, 39));
        label0_16->setFont(font4);
        label0_16->setAutoFillBackground(false);
        label0_17 = new QLabel(DoanhThu4);
        label0_17->setObjectName("label0_17");
        label0_17->setGeometry(QRect(30, 50, 252, 39));
        label0_17->setFont(font1);
        label0_17->setAutoFillBackground(false);
        label0_18 = new QLabel(DoanhThu4);
        label0_18->setObjectName("label0_18");
        label0_18->setGeometry(QRect(30, 160, 160, 39));
        label0_18->setFont(font1);
        label0_18->setAutoFillBackground(false);
        label0_19 = new QLabel(DoanhThu4);
        label0_19->setObjectName("label0_19");
        label0_19->setGeometry(QRect(470, 150, 75, 51));
        label0_19->setFont(font1);
        label0_19->setAutoFillBackground(false);
        label0_20 = new QLabel(DoanhThu4);
        label0_20->setObjectName("label0_20");
        label0_20->setGeometry(QRect(30, 100, 55, 36));
        label0_20->setFont(font1);
        label0_20->setAutoFillBackground(false);
        label0_21 = new QLabel(DoanhThu4);
        label0_21->setObjectName("label0_21");
        label0_21->setGeometry(QRect(250, 100, 72, 36));
        label0_21->setFont(font1);
        label0_21->setAutoFillBackground(false);
        pushButton_21 = new QPushButton(DoanhThu4);
        pushButton_21->setObjectName("pushButton_21");
        pushButton_21->setGeometry(QRect(720, 0, 151, 40));
        pushButton_21->setFont(font7);
        label_6 = new QLabel(DoanhThu4);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(200, 160, 261, 31));
        QFont font12;
        font12.setPointSize(20);
        font12.setBold(true);
        label_6->setFont(font12);
        dateEdit = new QDateEdit(DoanhThu4);
        dateEdit->setObjectName("dateEdit");
        dateEdit->setGeometry(QRect(90, 100, 121, 41));
        dateEdit_2 = new QDateEdit(DoanhThu4);
        dateEdit_2->setObjectName("dateEdit_2");
        dateEdit_2->setGeometry(QRect(330, 100, 121, 41));
        tableWidgetDSDoanhThu = new QTableWidget(DoanhThu4);
        if (tableWidgetDSDoanhThu->columnCount() < 8)
            tableWidgetDSDoanhThu->setColumnCount(8);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidgetDSDoanhThu->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidgetDSDoanhThu->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidgetDSDoanhThu->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidgetDSDoanhThu->setHorizontalHeaderItem(3, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWidgetDSDoanhThu->setHorizontalHeaderItem(4, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tableWidgetDSDoanhThu->setHorizontalHeaderItem(5, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tableWidgetDSDoanhThu->setHorizontalHeaderItem(6, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        tableWidgetDSDoanhThu->setHorizontalHeaderItem(7, __qtablewidgetitem7);
        tableWidgetDSDoanhThu->setObjectName("tableWidgetDSDoanhThu");
        tableWidgetDSDoanhThu->setGeometry(QRect(30, 220, 811, 291));
        QFont font13;
        font13.setPointSize(10);
        tableWidgetDSDoanhThu->setFont(font13);
        pushButtonXacNhanThongKeTheoThoiGian = new QPushButton(DoanhThu4);
        pushButtonXacNhanThongKeTheoThoiGian->setObjectName("pushButtonXacNhanThongKeTheoThoiGian");
        pushButtonXacNhanThongKeTheoThoiGian->setGeometry(QRect(510, 100, 131, 36));
        stackedWidget->addWidget(DoanhThu4);
        DanhSachDoanhThu5 = new QWidget();
        DanhSachDoanhThu5->setObjectName("DanhSachDoanhThu5");
        pushButton_25 = new QPushButton(DanhSachDoanhThu5);
        pushButton_25->setObjectName("pushButton_25");
        pushButton_25->setGeometry(QRect(720, -1, 151, 40));
        pushButton_25->setFont(font7);
        label0_6 = new QLabel(DanhSachDoanhThu5);
        label0_6->setObjectName("label0_6");
        label0_6->setGeometry(QRect(380, 0, 145, 39));
        label0_6->setFont(font4);
        label0_6->setAutoFillBackground(false);
        spinBoxSTTCanChinhSua = new QSpinBox(DanhSachDoanhThu5);
        spinBoxSTTCanChinhSua->setObjectName("spinBoxSTTCanChinhSua");
        spinBoxSTTCanChinhSua->setGeometry(QRect(380, 60, 131, 41));
        pushButtonXacNhanChonDonChinhSua = new QPushButton(DanhSachDoanhThu5);
        pushButtonXacNhanChonDonChinhSua->setObjectName("pushButtonXacNhanChonDonChinhSua");
        pushButtonXacNhanChonDonChinhSua->setGeometry(QRect(660, 62, 94, 41));
        tableWidgetDSToanBoDonHangGiaoDienChinhSua = new QTableWidget(DanhSachDoanhThu5);
        if (tableWidgetDSToanBoDonHangGiaoDienChinhSua->columnCount() < 8)
            tableWidgetDSToanBoDonHangGiaoDienChinhSua->setColumnCount(8);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        tableWidgetDSToanBoDonHangGiaoDienChinhSua->setHorizontalHeaderItem(0, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        tableWidgetDSToanBoDonHangGiaoDienChinhSua->setHorizontalHeaderItem(1, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        tableWidgetDSToanBoDonHangGiaoDienChinhSua->setHorizontalHeaderItem(2, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        tableWidgetDSToanBoDonHangGiaoDienChinhSua->setHorizontalHeaderItem(3, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        tableWidgetDSToanBoDonHangGiaoDienChinhSua->setHorizontalHeaderItem(4, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        tableWidgetDSToanBoDonHangGiaoDienChinhSua->setHorizontalHeaderItem(5, __qtablewidgetitem13);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        tableWidgetDSToanBoDonHangGiaoDienChinhSua->setHorizontalHeaderItem(6, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        tableWidgetDSToanBoDonHangGiaoDienChinhSua->setHorizontalHeaderItem(7, __qtablewidgetitem15);
        tableWidgetDSToanBoDonHangGiaoDienChinhSua->setObjectName("tableWidgetDSToanBoDonHangGiaoDienChinhSua");
        tableWidgetDSToanBoDonHangGiaoDienChinhSua->setGeometry(QRect(30, 132, 811, 371));
        tableWidgetDSToanBoDonHangGiaoDienChinhSua->setFont(font13);
        label0_43 = new QLabel(DanhSachDoanhThu5);
        label0_43->setObjectName("label0_43");
        label0_43->setGeometry(QRect(80, 62, 298, 36));
        label0_43->setFont(font1);
        label0_43->setAutoFillBackground(false);
        stackedWidget->addWidget(DanhSachDoanhThu5);
        TimTheoDiaChi6 = new QWidget();
        TimTheoDiaChi6->setObjectName("TimTheoDiaChi6");
        label0_23 = new QLabel(TimTheoDiaChi6);
        label0_23->setObjectName("label0_23");
        label0_23->setGeometry(QRect(330, 0, 219, 39));
        label0_23->setFont(font4);
        label0_23->setAutoFillBackground(false);
        label0_24 = new QLabel(TimTheoDiaChi6);
        label0_24->setObjectName("label0_24");
        label0_24->setGeometry(QRect(30, 70, 101, 36));
        label0_24->setFont(font1);
        label0_24->setAutoFillBackground(false);
        textSearch = new QTextEdit(TimTheoDiaChi6);
        textSearch->setObjectName("textSearch");
        textSearch->setGeometry(QRect(150, 70, 571, 41));
        textSearch->setFont(font11);
        pushButton_26 = new QPushButton(TimTheoDiaChi6);
        pushButton_26->setObjectName("pushButton_26");
        pushButton_26->setGeometry(QRect(720, 0, 151, 40));
        pushButton_26->setFont(font7);
        tableWidgetDSDiaChi = new QTableWidget(TimTheoDiaChi6);
        if (tableWidgetDSDiaChi->columnCount() < 8)
            tableWidgetDSDiaChi->setColumnCount(8);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        tableWidgetDSDiaChi->setHorizontalHeaderItem(0, __qtablewidgetitem16);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        tableWidgetDSDiaChi->setHorizontalHeaderItem(1, __qtablewidgetitem17);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        tableWidgetDSDiaChi->setHorizontalHeaderItem(2, __qtablewidgetitem18);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        tableWidgetDSDiaChi->setHorizontalHeaderItem(3, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        tableWidgetDSDiaChi->setHorizontalHeaderItem(4, __qtablewidgetitem20);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        tableWidgetDSDiaChi->setHorizontalHeaderItem(5, __qtablewidgetitem21);
        QTableWidgetItem *__qtablewidgetitem22 = new QTableWidgetItem();
        tableWidgetDSDiaChi->setHorizontalHeaderItem(6, __qtablewidgetitem22);
        QTableWidgetItem *__qtablewidgetitem23 = new QTableWidgetItem();
        tableWidgetDSDiaChi->setHorizontalHeaderItem(7, __qtablewidgetitem23);
        tableWidgetDSDiaChi->setObjectName("tableWidgetDSDiaChi");
        tableWidgetDSDiaChi->setGeometry(QRect(30, 140, 811, 371));
        tableWidgetDSDiaChi->setFont(font13);
        pushButton_7 = new QPushButton(TimTheoDiaChi6);
        pushButton_7->setObjectName("pushButton_7");
        pushButton_7->setGeometry(QRect(740, 70, 94, 41));
        stackedWidget->addWidget(TimTheoDiaChi6);
        page = new QWidget();
        page->setObjectName("page");
        label0_25 = new QLabel(page);
        label0_25->setObjectName("label0_25");
        label0_25->setGeometry(QRect(420, 0, 53, 39));
        label0_25->setFont(font4);
        label0_25->setAutoFillBackground(false);
        label0_26 = new QLabel(page);
        label0_26->setObjectName("label0_26");
        label0_26->setGeometry(QRect(80, 50, 298, 36));
        label0_26->setFont(font1);
        label0_26->setAutoFillBackground(false);
        tableWidgetDSToanBoDonHang = new QTableWidget(page);
        if (tableWidgetDSToanBoDonHang->columnCount() < 8)
            tableWidgetDSToanBoDonHang->setColumnCount(8);
        QTableWidgetItem *__qtablewidgetitem24 = new QTableWidgetItem();
        tableWidgetDSToanBoDonHang->setHorizontalHeaderItem(0, __qtablewidgetitem24);
        QTableWidgetItem *__qtablewidgetitem25 = new QTableWidgetItem();
        tableWidgetDSToanBoDonHang->setHorizontalHeaderItem(1, __qtablewidgetitem25);
        QTableWidgetItem *__qtablewidgetitem26 = new QTableWidgetItem();
        tableWidgetDSToanBoDonHang->setHorizontalHeaderItem(2, __qtablewidgetitem26);
        QTableWidgetItem *__qtablewidgetitem27 = new QTableWidgetItem();
        tableWidgetDSToanBoDonHang->setHorizontalHeaderItem(3, __qtablewidgetitem27);
        QTableWidgetItem *__qtablewidgetitem28 = new QTableWidgetItem();
        tableWidgetDSToanBoDonHang->setHorizontalHeaderItem(4, __qtablewidgetitem28);
        QTableWidgetItem *__qtablewidgetitem29 = new QTableWidgetItem();
        tableWidgetDSToanBoDonHang->setHorizontalHeaderItem(5, __qtablewidgetitem29);
        QTableWidgetItem *__qtablewidgetitem30 = new QTableWidgetItem();
        tableWidgetDSToanBoDonHang->setHorizontalHeaderItem(6, __qtablewidgetitem30);
        QTableWidgetItem *__qtablewidgetitem31 = new QTableWidgetItem();
        tableWidgetDSToanBoDonHang->setHorizontalHeaderItem(7, __qtablewidgetitem31);
        tableWidgetDSToanBoDonHang->setObjectName("tableWidgetDSToanBoDonHang");
        tableWidgetDSToanBoDonHang->setGeometry(QRect(30, 120, 811, 371));
        tableWidgetDSToanBoDonHang->setFont(font13);
        pushButtonXacNhanXoaDon = new QPushButton(page);
        pushButtonXacNhanXoaDon->setObjectName("pushButtonXacNhanXoaDon");
        pushButtonXacNhanXoaDon->setGeometry(QRect(660, 50, 94, 41));
        pushButton_24 = new QPushButton(page);
        pushButton_24->setObjectName("pushButton_24");
        pushButton_24->setGeometry(QRect(720, 0, 151, 40));
        pushButton_24->setFont(font7);
        spinBoxSTTCanXoa = new QSpinBox(page);
        spinBoxSTTCanXoa->setObjectName("spinBoxSTTCanXoa");
        spinBoxSTTCanXoa->setGeometry(QRect(280, 48, 131, 41));
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName("page_2");
        pushButtonXacNhanThemDon_2 = new QPushButton(page_2);
        pushButtonXacNhanThemDon_2->setObjectName("pushButtonXacNhanThemDon_2");
        pushButtonXacNhanThemDon_2->setGeometry(QRect(370, 480, 151, 41));
        pushButtonXacNhanThemDon_2->setFont(font8);
        label_7 = new QLabel(page_2);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(20, 420, 97, 28));
        label_7->setFont(font5);
        checkBoxDenChua_2 = new QCheckBox(page_2);
        checkBoxDenChua_2->setObjectName("checkBoxDenChua_2");
        checkBoxDenChua_2->setGeometry(QRect(440, 420, 275, 34));
        checkBoxDenChua_2->setFont(font5);
        label_9 = new QLabel(page_2);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(20, 320, 142, 28));
        label_9->setFont(font5);
        textEditTenNguoiNhan_2 = new QTextEdit(page_2);
        textEditTenNguoiNhan_2->setObjectName("textEditTenNguoiNhan_2");
        textEditTenNguoiNhan_2->setGeometry(QRect(190, 129, 461, 41));
        textEditTenNguoiNhan_2->setFont(font6);
        label_10 = new QLabel(page_2);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(480, 360, 52, 28));
        label_10->setFont(font5);
        doubleSpinBoxCanNang_2 = new QDoubleSpinBox(page_2);
        doubleSpinBoxCanNang_2->setObjectName("doubleSpinBoxCanNang_2");
        doubleSpinBoxCanNang_2->setGeometry(QRect(300, 350, 161, 41));
        label_29 = new QLabel(page_2);
        label_29->setObjectName("label_29");
        label_29->setGeometry(QRect(20, 140, 163, 28));
        label_29->setFont(font5);
        doubleSpinBoxQuangDuong_2 = new QDoubleSpinBox(page_2);
        doubleSpinBoxQuangDuong_2->setObjectName("doubleSpinBoxQuangDuong_2");
        doubleSpinBoxQuangDuong_2->setGeometry(QRect(670, 260, 161, 41));
        radioButtonBuuKien_2 = new QRadioButton(page_2);
        radioButtonBuuKien_2->setObjectName("radioButtonBuuKien_2");
        radioButtonBuuKien_2->setGeometry(QRect(180, 360, 113, 34));
        radioButtonBuuKien_2->setFont(font5);
        label0_7 = new QLabel(page_2);
        label0_7->setObjectName("label0_7");
        label0_7->setGeometry(QRect(430, 10, 81, 41));
        label0_7->setFont(font4);
        label0_7->setAutoFillBackground(false);
        label_17 = new QLabel(page_2);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(20, 201, 73, 28));
        label_17->setFont(font5);
        dateEditNgayGui_2 = new QDateEdit(page_2);
        dateEditNgayGui_2->setObjectName("dateEditNgayGui_2");
        dateEditNgayGui_2->setGeometry(QRect(130, 420, 111, 31));
        dateEditNgayGui_2->setFont(font8);
        label_30 = new QLabel(page_2);
        label_30->setObjectName("label_30");
        label_30->setGeometry(QRect(20, 80, 138, 28));
        label_30->setFont(font5);
        dateEditNgayNhan_2 = new QDateEdit(page_2);
        dateEditNgayNhan_2->setObjectName("dateEditNgayNhan_2");
        dateEditNgayNhan_2->setGeometry(QRect(720, 420, 111, 31));
        dateEditNgayNhan_2->setFont(font8);
        textEditDiaChiGui_2 = new QTextEdit(page_2);
        textEditDiaChiGui_2->setObjectName("textEditDiaChiGui_2");
        textEditDiaChiGui_2->setGeometry(QRect(120, 190, 461, 41));
        textEditDiaChiGui_2->setFont(font6);
        pushButton_27 = new QPushButton(page_2);
        pushButton_27->setObjectName("pushButton_27");
        pushButton_27->setGeometry(QRect(720, 10, 151, 40));
        pushButton_27->setFont(font7);
        textEditDiaChiNhan_2 = new QTextEdit(page_2);
        textEditDiaChiNhan_2->setObjectName("textEditDiaChiNhan_2");
        textEditDiaChiNhan_2->setGeometry(QRect(120, 260, 461, 41));
        textEditDiaChiNhan_2->setFont(font6);
        label_18 = new QLabel(page_2);
        label_18->setObjectName("label_18");
        label_18->setGeometry(QRect(20, 270, 90, 28));
        label_18->setFont(font5);
        textEditTenNguoiGui_2 = new QTextEdit(page_2);
        textEditTenNguoiGui_2->setObjectName("textEditTenNguoiGui_2");
        textEditTenNguoiGui_2->setGeometry(QRect(170, 70, 481, 41));
        textEditTenNguoiGui_2->setFont(font6);
        label_19 = new QLabel(page_2);
        label_19->setObjectName("label_19");
        label_19->setGeometry(QRect(680, 220, 138, 28));
        label_19->setFont(font5);
        radioButtonTaiLieu_2 = new QRadioButton(page_2);
        radioButtonTaiLieu_2->setObjectName("radioButtonTaiLieu_2");
        radioButtonTaiLieu_2->setGeometry(QRect(180, 320, 94, 34));
        radioButtonTaiLieu_2->setFont(font5);
        stackedWidget->addWidget(page_2);
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName("menubar");
        menubar->setGeometry(QRect(0, 0, 904, 25));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName("statusbar");
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(8);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        label0->setText(QCoreApplication::translate("MainWindow", "Giao di\341\273\207n ch\303\255nh", nullptr));
        pushButton_1->setText(QString());
        pushButton_2->setText(QCoreApplication::translate("MainWindow", "Th\303\252m", nullptr));
        pushButton_3->setText(QCoreApplication::translate("MainWindow", "C\341\272\255p nh\341\272\255t gi\303\241", nullptr));
        pushButton_4->setText(QCoreApplication::translate("MainWindow", "T\303\254m theo \304\221\341\273\213a ch\341\273\211", nullptr));
        pushButtonThongKe->setText(QCoreApplication::translate("MainWindow", "Th\341\273\221ng k\303\252", nullptr));
        pushButtonGiaoDienXoaDon->setText(QCoreApplication::translate("MainWindow", "X\303\263a", nullptr));
        pushButtonGiaoDienChinhSuaDon->setText(QCoreApplication::translate("MainWindow", "Ch\341\273\211nh", nullptr));
        label0_2->setText(QCoreApplication::translate("MainWindow", "Th\303\252m", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "\304\220/c g\341\273\255i", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "\304\220/c nh\341\272\255n", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", " Ng\303\240y g\341\273\255i", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "Lo\341\272\241i \304\221\306\241n h\303\240ng", nullptr));
        radioButtonTaiLieu->setText(QCoreApplication::translate("MainWindow", "T\303\240i li\341\273\207u", nullptr));
        checkBoxDenChua->setText(QCoreApplication::translate("MainWindow", "\304\220\306\241n h\303\240ng \304\221\303\243 g\341\273\255i t\341\273\233i h\303\264m", nullptr));
        radioButtonBuuKien->setText(QCoreApplication::translate("MainWindow", "B\306\260u ki\341\273\207n", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "Qu\303\243ng \304\221\306\260\341\273\235ng", nullptr));
        label_8->setText(QCoreApplication::translate("MainWindow", "KG", nullptr));
        pushButton_23->setText(QCoreApplication::translate("MainWindow", "Giao di\341\273\207n ch\303\255nh", nullptr));
        pushButtonXacNhanThemDon->setText(QCoreApplication::translate("MainWindow", "X\303\241c nh\341\272\255n", nullptr));
        label_25->setText(QCoreApplication::translate("MainWindow", "T\303\252n ng\306\260\341\273\235i g\341\273\255i", nullptr));
        label_26->setText(QCoreApplication::translate("MainWindow", "T\303\252n Ng\306\260\341\273\235i Nh\341\272\255n", nullptr));
        label0_3->setText(QCoreApplication::translate("MainWindow", "\304\220\306\241n h\303\240ng \304\221\303\243 \304\221\306\260\341\273\243c th\303\252m th\303\240nh c\303\264ng", nullptr));
        label0_4->setText(QCoreApplication::translate("MainWindow", "M\303\243 v\341\272\255n \304\221\306\241n l\303\240 :", nullptr));
        label0_5->setText(QCoreApplication::translate("MainWindow", "Th\303\264ng tin :", nullptr));
        label_28->setText(QCoreApplication::translate("MainWindow", "T\303\252n ng\306\260\341\273\235i g\341\273\255i", nullptr));
        label_27->setText(QCoreApplication::translate("MainWindow", "T\303\252n ng\306\260\341\273\235i nh\341\272\255n", nullptr));
        label_11->setText(QCoreApplication::translate("MainWindow", "\304\220/c g\341\273\255i", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindow", "\304\220/c nh\341\272\255n", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "Qu\303\243ng \304\221\306\260\341\273\235ng", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindow", "Ng\303\240y g\341\273\255i", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "Lo\341\272\241i \304\221\306\241n h\303\240ng", nullptr));
        label_16->setText(QCoreApplication::translate("MainWindow", "\304\220\306\241n h\303\240ng \304\221\303\243 g\341\273\255i t\341\273\233i h\303\264m", nullptr));
        pushButton_18->setText(QCoreApplication::translate("MainWindow", "Ch\341\273\211nh s\341\273\255a", nullptr));
        pushButton_20->setText(QCoreApplication::translate("MainWindow", "Giao di\341\273\207n ch\303\255nh", nullptr));
        labelID->setText(QString());
        labelTenNguoiGui->setText(QString());
        labelTenNguoiNhan->setText(QString());
        labelDiaChiGui->setText(QString());
        labelDiaChiNhan->setText(QString());
        labelQuangDuong->setText(QString());
        labelNgayThangNamGui->setText(QString());
        labelTaiLieuHayBuuKien->setText(QString());
        labelNgayThangNamNhan->setText(QString());
        label0_11->setText(QCoreApplication::translate("MainWindow", "C\341\272\255p nh\341\272\255t gi\303\241", nullptr));
        checkBoxTaiLieu->setText(QCoreApplication::translate("MainWindow", "T\303\240i li\341\273\207u", nullptr));
        checkBoxBuuKien->setText(QCoreApplication::translate("MainWindow", "B\306\260u ki\341\273\207n", nullptr));
        label_35->setText(QCoreApplication::translate("MainWindow", "Gi\303\241 nh\341\272\255n \304\221\306\241n :", nullptr));
        label_36->setText(QCoreApplication::translate("MainWindow", "Gi\303\241 Kilometer :", nullptr));
        label_37->setText(QCoreApplication::translate("MainWindow", "Gi\303\241 c\303\242n n\341\272\267ng :", nullptr));
        label_38->setText(QCoreApplication::translate("MainWindow", "Gi\303\241 Kilometer :", nullptr));
        label0_12->setText(QCoreApplication::translate("MainWindow", "-->", nullptr));
        label0_13->setText(QCoreApplication::translate("MainWindow", "-->", nullptr));
        label0_14->setText(QCoreApplication::translate("MainWindow", "-->", nullptr));
        label0_15->setText(QCoreApplication::translate("MainWindow", "-->", nullptr));
        pushButtonDatVeMacDinh->setText(QCoreApplication::translate("MainWindow", "\304\220\341\272\267t v\341\273\201 m\341\272\267c \304\221\341\273\213nh", nullptr));
        pushButtonCapNhatGia->setText(QCoreApplication::translate("MainWindow", "L\306\260u", nullptr));
        pushButton_22->setText(QCoreApplication::translate("MainWindow", "Giao di\341\273\207n ch\303\255nh", nullptr));
        labelGiaNhanDonTaiLieu->setText(QString());
        labelGiaQuangDuongTaiLieu->setText(QString());
        labelGiaCanNangBuuKien->setText(QString());
        labelGiaQuangDuongBuuKien->setText(QString());
        label0_16->setText(QCoreApplication::translate("MainWindow", "Th\341\273\221ng k\303\252 \304\221\306\241n \304\221\303\243 g\341\273\255i \304\221\341\272\277n th\303\240nh c\303\264ng", nullptr));
        label0_17->setText(QCoreApplication::translate("MainWindow", "Kho\341\272\243ng th\341\273\235i gian :", nullptr));
        label0_18->setText(QCoreApplication::translate("MainWindow", "Doanh thu :", nullptr));
        label0_19->setText(QCoreApplication::translate("MainWindow", "\304\220\341\273\223ng", nullptr));
        label0_20->setText(QCoreApplication::translate("MainWindow", "T\341\273\253 : ", nullptr));
        label0_21->setText(QCoreApplication::translate("MainWindow", "\304\220\341\272\277n : ", nullptr));
        pushButton_21->setText(QCoreApplication::translate("MainWindow", "Giao di\341\273\207n ch\303\255nh", nullptr));
        label_6->setText(QString());
        QTableWidgetItem *___qtablewidgetitem = tableWidgetDSDoanhThu->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("MainWindow", "T\303\252n ng\306\260\341\273\235i g\341\273\255i", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidgetDSDoanhThu->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("MainWindow", "\304\220\341\273\213a ch\341\273\211 g\341\273\255i", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidgetDSDoanhThu->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("MainWindow", "T\303\252n ng\306\260\341\273\235i nh\341\272\255n", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidgetDSDoanhThu->horizontalHeaderItem(3);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("MainWindow", "\304\220\341\273\213a ch\341\273\211 nh\341\272\255n", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidgetDSDoanhThu->horizontalHeaderItem(4);
        ___qtablewidgetitem4->setText(QCoreApplication::translate("MainWindow", "Ng\303\240y g\341\273\255i", nullptr));
        QTableWidgetItem *___qtablewidgetitem5 = tableWidgetDSDoanhThu->horizontalHeaderItem(5);
        ___qtablewidgetitem5->setText(QCoreApplication::translate("MainWindow", "Ng\303\240y nh\341\272\255n", nullptr));
        QTableWidgetItem *___qtablewidgetitem6 = tableWidgetDSDoanhThu->horizontalHeaderItem(6);
        ___qtablewidgetitem6->setText(QCoreApplication::translate("MainWindow", "Lo\341\272\241i \304\221\306\241n h\303\240ng", nullptr));
        QTableWidgetItem *___qtablewidgetitem7 = tableWidgetDSDoanhThu->horizontalHeaderItem(7);
        ___qtablewidgetitem7->setText(QCoreApplication::translate("MainWindow", "Thu \304\221\306\260\341\273\243c", nullptr));
        pushButtonXacNhanThongKeTheoThoiGian->setText(QCoreApplication::translate("MainWindow", "X\303\241c nh\341\272\255n", nullptr));
        pushButton_25->setText(QCoreApplication::translate("MainWindow", "Giao di\341\273\207n ch\303\255nh", nullptr));
        label0_6->setText(QCoreApplication::translate("MainWindow", "\304\220i\341\273\201u ch\341\273\211nh", nullptr));
        pushButtonXacNhanChonDonChinhSua->setText(QCoreApplication::translate("MainWindow", "X\303\241c nh\341\272\255n", nullptr));
        QTableWidgetItem *___qtablewidgetitem8 = tableWidgetDSToanBoDonHangGiaoDienChinhSua->horizontalHeaderItem(0);
        ___qtablewidgetitem8->setText(QCoreApplication::translate("MainWindow", "T\303\252n ng\306\260\341\273\235i g\341\273\255i", nullptr));
        QTableWidgetItem *___qtablewidgetitem9 = tableWidgetDSToanBoDonHangGiaoDienChinhSua->horizontalHeaderItem(1);
        ___qtablewidgetitem9->setText(QCoreApplication::translate("MainWindow", "\304\220\341\273\213a ch\341\273\211 g\341\273\255i", nullptr));
        QTableWidgetItem *___qtablewidgetitem10 = tableWidgetDSToanBoDonHangGiaoDienChinhSua->horizontalHeaderItem(2);
        ___qtablewidgetitem10->setText(QCoreApplication::translate("MainWindow", "T\303\252n ng\306\260\341\273\235i nh\341\272\255n", nullptr));
        QTableWidgetItem *___qtablewidgetitem11 = tableWidgetDSToanBoDonHangGiaoDienChinhSua->horizontalHeaderItem(3);
        ___qtablewidgetitem11->setText(QCoreApplication::translate("MainWindow", "\304\220\341\273\213a ch\341\273\211 nh\341\272\255n", nullptr));
        QTableWidgetItem *___qtablewidgetitem12 = tableWidgetDSToanBoDonHangGiaoDienChinhSua->horizontalHeaderItem(4);
        ___qtablewidgetitem12->setText(QCoreApplication::translate("MainWindow", "Ng\303\240y g\341\273\255i", nullptr));
        QTableWidgetItem *___qtablewidgetitem13 = tableWidgetDSToanBoDonHangGiaoDienChinhSua->horizontalHeaderItem(5);
        ___qtablewidgetitem13->setText(QCoreApplication::translate("MainWindow", "Ng\303\240y nh\341\272\255n", nullptr));
        QTableWidgetItem *___qtablewidgetitem14 = tableWidgetDSToanBoDonHangGiaoDienChinhSua->horizontalHeaderItem(6);
        ___qtablewidgetitem14->setText(QCoreApplication::translate("MainWindow", "Lo\341\272\241i \304\221\306\241n h\303\240ng", nullptr));
        QTableWidgetItem *___qtablewidgetitem15 = tableWidgetDSToanBoDonHangGiaoDienChinhSua->horizontalHeaderItem(7);
        ___qtablewidgetitem15->setText(QCoreApplication::translate("MainWindow", "Thu \304\221\306\260\341\273\243c", nullptr));
        label0_43->setText(QCoreApplication::translate("MainWindow", "STT c\341\272\247n ch\341\273\211nh s\341\273\255a", nullptr));
        label0_23->setText(QCoreApplication::translate("MainWindow", "T\303\254m theo \304\221\341\273\213a ch\341\273\211", nullptr));
        label0_24->setText(QCoreApplication::translate("MainWindow", "\304\220\341\273\213a ch\341\273\211 :", nullptr));
        pushButton_26->setText(QCoreApplication::translate("MainWindow", "Giao di\341\273\207n ch\303\255nh", nullptr));
        QTableWidgetItem *___qtablewidgetitem16 = tableWidgetDSDiaChi->horizontalHeaderItem(0);
        ___qtablewidgetitem16->setText(QCoreApplication::translate("MainWindow", "T\303\252n ng\306\260\341\273\235i g\341\273\255i", nullptr));
        QTableWidgetItem *___qtablewidgetitem17 = tableWidgetDSDiaChi->horizontalHeaderItem(1);
        ___qtablewidgetitem17->setText(QCoreApplication::translate("MainWindow", "\304\220\341\273\213a ch\341\273\211 g\341\273\255i", nullptr));
        QTableWidgetItem *___qtablewidgetitem18 = tableWidgetDSDiaChi->horizontalHeaderItem(2);
        ___qtablewidgetitem18->setText(QCoreApplication::translate("MainWindow", "T\303\252n ng\306\260\341\273\235i nh\341\272\255n", nullptr));
        QTableWidgetItem *___qtablewidgetitem19 = tableWidgetDSDiaChi->horizontalHeaderItem(3);
        ___qtablewidgetitem19->setText(QCoreApplication::translate("MainWindow", "\304\220\341\273\213a ch\341\273\211 nh\341\272\255n", nullptr));
        QTableWidgetItem *___qtablewidgetitem20 = tableWidgetDSDiaChi->horizontalHeaderItem(4);
        ___qtablewidgetitem20->setText(QCoreApplication::translate("MainWindow", "Ng\303\240y g\341\273\255i", nullptr));
        QTableWidgetItem *___qtablewidgetitem21 = tableWidgetDSDiaChi->horizontalHeaderItem(5);
        ___qtablewidgetitem21->setText(QCoreApplication::translate("MainWindow", "Ng\303\240y nh\341\272\255n", nullptr));
        QTableWidgetItem *___qtablewidgetitem22 = tableWidgetDSDiaChi->horizontalHeaderItem(6);
        ___qtablewidgetitem22->setText(QCoreApplication::translate("MainWindow", "Lo\341\272\241i \304\221\306\241n h\303\240ng", nullptr));
        QTableWidgetItem *___qtablewidgetitem23 = tableWidgetDSDiaChi->horizontalHeaderItem(7);
        ___qtablewidgetitem23->setText(QCoreApplication::translate("MainWindow", "Thu \304\221\306\260\341\273\243c", nullptr));
        pushButton_7->setText(QCoreApplication::translate("MainWindow", "X\303\241c nh\341\272\255n", nullptr));
        label0_25->setText(QCoreApplication::translate("MainWindow", "X\303\263a", nullptr));
        label0_26->setText(QCoreApplication::translate("MainWindow", "STT c\341\272\247n x\303\263a:", nullptr));
        QTableWidgetItem *___qtablewidgetitem24 = tableWidgetDSToanBoDonHang->horizontalHeaderItem(0);
        ___qtablewidgetitem24->setText(QCoreApplication::translate("MainWindow", "T\303\252n ng\306\260\341\273\235i g\341\273\255i", nullptr));
        QTableWidgetItem *___qtablewidgetitem25 = tableWidgetDSToanBoDonHang->horizontalHeaderItem(1);
        ___qtablewidgetitem25->setText(QCoreApplication::translate("MainWindow", "\304\220\341\273\213a ch\341\273\211 g\341\273\255i", nullptr));
        QTableWidgetItem *___qtablewidgetitem26 = tableWidgetDSToanBoDonHang->horizontalHeaderItem(2);
        ___qtablewidgetitem26->setText(QCoreApplication::translate("MainWindow", "T\303\252n ng\306\260\341\273\235i nh\341\272\255n", nullptr));
        QTableWidgetItem *___qtablewidgetitem27 = tableWidgetDSToanBoDonHang->horizontalHeaderItem(3);
        ___qtablewidgetitem27->setText(QCoreApplication::translate("MainWindow", "\304\220\341\273\213a ch\341\273\211 nh\341\272\255n", nullptr));
        QTableWidgetItem *___qtablewidgetitem28 = tableWidgetDSToanBoDonHang->horizontalHeaderItem(4);
        ___qtablewidgetitem28->setText(QCoreApplication::translate("MainWindow", "Ng\303\240y g\341\273\255i", nullptr));
        QTableWidgetItem *___qtablewidgetitem29 = tableWidgetDSToanBoDonHang->horizontalHeaderItem(5);
        ___qtablewidgetitem29->setText(QCoreApplication::translate("MainWindow", "Ng\303\240y nh\341\272\255n", nullptr));
        QTableWidgetItem *___qtablewidgetitem30 = tableWidgetDSToanBoDonHang->horizontalHeaderItem(6);
        ___qtablewidgetitem30->setText(QCoreApplication::translate("MainWindow", "Lo\341\272\241i \304\221\306\241n h\303\240ng", nullptr));
        QTableWidgetItem *___qtablewidgetitem31 = tableWidgetDSToanBoDonHang->horizontalHeaderItem(7);
        ___qtablewidgetitem31->setText(QCoreApplication::translate("MainWindow", "Thu \304\221\306\260\341\273\243c", nullptr));
        pushButtonXacNhanXoaDon->setText(QCoreApplication::translate("MainWindow", "X\303\241c nh\341\272\255n", nullptr));
        pushButton_24->setText(QCoreApplication::translate("MainWindow", "Giao di\341\273\207n ch\303\255nh", nullptr));
        pushButtonXacNhanThemDon_2->setText(QCoreApplication::translate("MainWindow", "X\303\241c nh\341\272\255n", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", " Ng\303\240y g\341\273\255i", nullptr));
        checkBoxDenChua_2->setText(QCoreApplication::translate("MainWindow", "\304\220\306\241n h\303\240ng \304\221\303\243 g\341\273\255i t\341\273\233i h\303\264m", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindow", "Lo\341\272\241i \304\221\306\241n h\303\240ng", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindow", "KG", nullptr));
        label_29->setText(QCoreApplication::translate("MainWindow", "T\303\252n Ng\306\260\341\273\235i Nh\341\272\255n", nullptr));
        radioButtonBuuKien_2->setText(QCoreApplication::translate("MainWindow", "B\306\260u ki\341\273\207n", nullptr));
        label0_7->setText(QCoreApplication::translate("MainWindow", "\304\220i\341\273\201u ch\341\273\211nh", nullptr));
        label_17->setText(QCoreApplication::translate("MainWindow", "\304\220/c g\341\273\255i", nullptr));
        label_30->setText(QCoreApplication::translate("MainWindow", "T\303\252n ng\306\260\341\273\235i g\341\273\255i", nullptr));
        pushButton_27->setText(QCoreApplication::translate("MainWindow", "Giao di\341\273\207n ch\303\255nh", nullptr));
        label_18->setText(QCoreApplication::translate("MainWindow", "\304\220/c nh\341\272\255n", nullptr));
        label_19->setText(QCoreApplication::translate("MainWindow", "Qu\303\243ng \304\221\306\260\341\273\235ng", nullptr));
        radioButtonTaiLieu_2->setText(QCoreApplication::translate("MainWindow", "T\303\240i li\341\273\207u", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
